### PR TITLE
Create camtasia2023.sh

### PR DESCRIPTION
**Pull request by beatlemike**
Added camtasia2023 label, this will supersede camtasia2022

### CODE REVIEW

**Comment by duderin0** [comment]
Do we want to follow the previous convention where the latest version gets the default name without the year as well? Currently for 2022 its:
camtasia|\
camtasia2022)

**Comment by beatlemike** [comment]
I think that makes sense. I noticed the fragment for 2022 is just named "camtasia.sh". So would technically that need to be updated with the camtasia2023 label, and a "camtasia2022.sh" be created?

**Comment by scriptingosx** [comment]
yes, I agree on the file name change. Follow-up question: can we retire some of the labels for the older versions or are those versions of the app still supported?

**Comment by scriptingosx** [comment]
I changed the file and label names in the commit above. Thank you!

(Still expecting feedback on whether we can or should delete old labels here.)

**Comment by beatlemike** [comment]
> yes, I agree on the file name change. Follow-up question: can we retire some of the labels for the older versions or are those versions of the app still supported?

I can't speak to that directly. When a. new version comes out, they do discontinue updating the previous version. But the do make versions back to 2012 available for download. I would say Leaner and Meaner. Maybe drop all but the last 1 or 2 versions?

**Comment by beatlemike** [comment]
and thank you my friend.

**Pull request merged**
