### PR TITLE
Download with extra sets of headers

### PR DESCRIPTION
**Pull request by Theile**
In the `buildLabel.sh` script, I had to add extra download options using different sets of headers in order for the server to return the file. 

Then came some “mocha”-labels, and a new set of headers had to be found for those. And to even download from the server once the URL was given, the server needed these headers. So __Installomator__ needs to be able to try these same sets of headers for the download, so we can get it to work.

Maybe we can figure out in the fuse to somehow determine automatically which headers are needed for a certain server, but until then, my method is to download from a browser (Safari or Brave), and then inspect what headers it used for the download.

The 3 sets of headers has been added to both scripts now, in the same order, and as clear as can be done, so the differences is more obvious.

### CODE REVIEW

**Comment by scriptingosx** [comment]
Instead of trying repeatedly with different sets of headers, I think we should define custom curl options in the label and then use those in the download:

in the label:

```
curlOptions="-H \"User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15\" \
-H \"accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\" \
-H \"accept-encoding: gzip, deflate, br\" \
-H \"accept-language: en-US,en;q=0.9\" \
-H \"sec-fetch-dest: document\" \
-H \"sec-fetch-mode: navigate\" \
-H \"sec-fetch-user: ?1\" \
-H \"sec-gpc: 1\" \
-H \"upgrade-insecure-requests: 1\" "
```

and then where the actual download happens: 
```
curl -fsL ${=curlOptions} "$downloadURL" -o "$archiveName"
```

**Comment by Theile** [comment]
Thanks, I think this is much better approach, too.

I do however get an error when downloading, but the quoting seems a little "wild". Do you know what happens here:
```
2022-01-11 12:03:04 mochatn3270 Downloading https://mochasoft.dk/tn3270.dmg.zip to TN3270.zip
+/Users/st/Documents/GitHub/Installomator/build/Installomator.sh:4419> curl -fsL -H '"User-Agent:' Mozilla/5.0 '(Macintosh;' Intel Mac OS X '10_15_7)' AppleWebKit/605.1.15 '(KHTML,' like 'Gecko)' Version/15.1 'Safari/605.1.15"' -H '"accept:' 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"' -H '"accept-encoding:' gzip, deflate, 'br"' -H '"accept-language:' 'en-US,en;q=0.9"' -H '"sec-fetch-dest:' 'document"' -H '"sec-fetch-mode:' 'navigate"' -H '"sec-fetch-user:' '?1"' -H '"sec-gpc:' '1"' -H '"upgrade-insecure-requests:' '1"' https://mochasoft.dk/tn3270.dmg.zip -o TN3270.zip
+/Users/st/Documents/GitHub/Installomator/build/Installomator.sh:4420> printlog 'error downloading https://mochasoft.dk/tn3270.dmg.zip'
```

**Comment by Theile** [comment]
So I have tested a bit back and forth, and this line
```
curl -fsL ${=curlOptions} "$downloadURL" -o "$archiveName"
```

Will give this result:
```
curl -fL -H '"User-Agent:' Mozilla/5.0 '(Macintosh;' Intel Mac OS X '10_15_7)' AppleWebKit/605.1.15 '(KHTML,' like 'Gecko)' Version/15.1 'Safari/605.1.15"' -H '"accept:' 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"' -H '"accept-encoding:' gzip, deflate, 'br"' -H '"accept-language:' 'en-US,en;q=0.9"' -H '"sec-fetch-dest:' 'document"' -H '"sec-fetch-mode:' 'navigate"' -H '"sec-fetch-user:' '?1"' -H '"sec-gpc:' '1"' -H '"upgrade-insecure-requests:' '1"' https://mochasoft.dk/tn3270.dmg.zip -o TN3270.zip
```

So I changed it to this:
```
curl -fsL ${curlOptions} "$downloadURL" -o "$archiveName"
```

And then I get this result:
```
curl -fsL '-H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15" -H "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" -H "accept-encoding: gzip, deflate, br" -H "accept-language: en-US,en;q=0.9" -H "sec-fetch-dest: document" -H "sec-fetch-mode: navigate" -H "sec-fetch-user: ?1" -H "sec-gpc: 1" -H "upgrade-insecure-requests: 1" ' https://mochasoft.dk/tn3270.dmg.zip -o TN3270.zip
```

Those extra `' '` that are surrounding `curlOptions` makes it not working.

Suggestions to how to fix this?

**Comment by scriptingosx** [comment]
took me a while to figure that out, too. Turns out, the easiest way is to define `curlOptions` as an array:
```
curlOptions=( -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15"
-H "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
-H "accept-encoding: gzip, deflate, br"
-H "accept-language: en-US,en;q=0.9"
-H "sec-fetch-dest: document" 
-H "sec-fetch-mode: navigate"
-H "sec-fetch-user: ?1"
-H "sec-gpc: 1"
-H "upgrade-insecure-requests: 1" )

curl -fsL ${curlOptions} "$downloadURL" -o "$archiveName"
```

sorry for the confusion

**Comment by Theile** [comment]
But that is even more beautiful in the label, and it works great!

**Comment by Theile** [comment]
`checkLabels.sh` should be updated as well. Hopefully done later tonight.

**Comment by apizz** [comment]
This was my most recent run of `buildLabel.sh` for mochatn3270:
```
./utils/buildLabel.sh https://mochasoft.dk/tn3270.dmg.zip
Changing directory to /Users/installomator/Documents/git/Installomator/2022-01-19-17-04-48
Working dir: /Users/installomator/Documents/git/Installomator/2022-01-19-17-04-48
Downloading https://mochasoft.dk/tn3270.dmg.zip
tn3270.dmg.zip
Redirecting to (maybe this can help us with version):
HTTP/2 400 
content-length: 339
content-type: text/html; charset=us-ascii
server: Microsoft-HTTPAPI/2.0
date: Wed, 19 Jan 2022 22:04:49 GMT

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  1346    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 406
error downloading https://mochasoft.dk/tn3270.dmg.zip with no headers.
result: tn3270.dmg.zip
https://mochasoft.dk/tn3270.dmg.zip
Trying 1st set of extra headers to download.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5934k  100 5934k    0     0  2276k      0  0:00:02  0:00:02 --:--:-- 2279k
archiveTempName: tn3270.dmg.zip
archivePath: https://mochasoft.dk/tn3270.dmg.zip
Calculated archiveName: tn3270.dmg.zip
name: tn3270.dmg
archiveExt: zip
Compressed file found
Disk image found: /Users/installomator/Documents/git/Installomator/2022-01-19-17-04-48/tn3270.dmg
archiveExt: dmgInZip
DMG investigation.
Mounting /Users/installomator/Documents/git/Installomator/2022-01-19-17-04-48/tn3270.dmg
Mounted: /Volumes/Mocha TN3270 for macOS
App found: /Volumes/Mocha TN3270 for macOS/TN3270.app
Application investigation.
Team ID found for app: RR9F5EPNVW
"disk4" ejected.
identifier: tn3270

**********

Labels should be named in small caps, numbers 0-9, “-”, and “_”. No other characters allowed.

appNewVersion is often difficult to find. Can sometimes be found in the filename, sometimes as part of the download redirects, but also on a web page. See redirect and archivePath above if link contains information about this. That is a good place to start

tn3270)
    name="TN3270"
    type="appInDmgInZip"
    downloadURL="https://mochasoft.dk/tn3270.dmg.zip"
    appNewVersion=""
    expectedTeamID="RR9F5EPNVW"
    ;;

Above should be saved in a file with exact same name as label, and given extension “.sh”.
Put this file in folder “fragments/labels”.
```

**Comment by apizz** [comment]
Output running `./assemble.sh mochatn3270 DEBUG=1`:
```
./assemble.sh mochatn3270 DEBUG=1
2022-01-19 17:08:05 mochatn3270 setting variable from argument DEBUG=1
2022-01-19 17:08:05 mochatn3270 ################## Start Installomator v. 9.0dev
2022-01-19 17:08:05 mochatn3270 ################## mochatn3270
2022-01-19 17:08:05 mochatn3270 DEBUG mode 1 enabled.
2022-01-19 17:08:05 mochatn3270 BLOCKING_PROCESS_ACTION=tell_user
2022-01-19 17:08:05 mochatn3270 NOTIFY=success
2022-01-19 17:08:05 mochatn3270 LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2022-01-19 17:08:05 mochatn3270 no blocking processes defined, using TN3270 as default
2022-01-19 17:08:05 mochatn3270 Changing directory to /Users/installomator/Documents/git/Installomator/build
2022-01-19 17:08:05 mochatn3270 App(s) found: 
2022-01-19 17:08:05 mochatn3270 could not find TN3270.app
2022-01-19 17:08:05 mochatn3270 appversion: 
2022-01-19 17:08:05 mochatn3270 Latest version not specified.
2022-01-19 17:08:05 mochatn3270 Downloading https://mochasoft.dk/tn3270.dmg.zip to TN3270.zip
2022-01-19 17:08:07 mochatn3270 DEBUG mode 1, not checking for blocking processes
2022-01-19 17:08:07 mochatn3270 Installing TN3270
2022-01-19 17:08:07 mochatn3270 Unzipping TN3270.zip
2022-01-19 17:08:07 mochatn3270 found dmg: /Users/installomator/Documents/git/Installomator/build/tn3270.dmg
2022-01-19 17:08:07 mochatn3270 Mounting /Users/installomator/Documents/git/Installomator/build/tn3270.dmg
2022-01-19 17:08:07 mochatn3270 Mounted: /Volumes/Mocha TN3270 for macOS
2022-01-19 17:08:07 mochatn3270 Verifying: /Volumes/Mocha TN3270 for macOS/TN3270.app
2022-01-19 17:08:08 mochatn3270 Team ID matching: RR9F5EPNVW (expected: RR9F5EPNVW )
2022-01-19 17:08:08 mochatn3270 Downloaded version of TN3270 is 2.6.1 (replacing version ).
2022-01-19 17:08:08 mochatn3270 App has LSMinimumSystemVersion: 10.9
2022-01-19 17:08:08 mochatn3270 DEBUG mode 1 enabled, skipping remove, copy and chown steps
2022-01-19 17:08:08 mochatn3270 Finishing...
2022-01-19 17:08:18 mochatn3270 App(s) found: 
2022-01-19 17:08:18 mochatn3270 could not find TN3270.app
2022-01-19 17:08:18 mochatn3270 Installed TN3270
2022-01-19 17:08:18 mochatn3270 notifying
2022-01-19 17:08:18 mochatn3270 Unmounting /Volumes/Mocha TN3270 for macOS
"disk4" ejected.
2022-01-19 17:08:19 mochatn3270 DEBUG mode 1, not reopening anything
2022-01-19 17:08:19 mochatn3270 ################## End Installomator, exit code 0
```

**Comment by apizz** [comment]
Thanks for your work on this!

**Pull request merged**
