### PR TITLE
Correct download url of libreoffice.

### PR DESCRIPTION
**Pull request by taniguti**
- libreoffice download url has been changed. Correct URL and add '-L' switch for curl.  https://github.com/Installomator/Installomator/pull/672/commits/6876114fdf5c9c476fa444e13544c241cd0c9498

### CODE REVIEW

**Comment by cfsnate** [comment]
Confirmed this resolved Libreoffice issues

**Comment by Theile** [comment]
Can you please remove the changes to `functions.sh`?

I am working on fixing the GitHub issue in #659.

**Comment by taniguti** [comment]
@Theile 
Oh. Ok. 
I removed function.sh from this PR.

**Comment by Theile** [comment]
Thanks @taniguti! Looks great!

**Comment by scriptingosx** [comment]
Thank you!

**Pull request merged**
