### PR TITLE
Create displaylinkmanager.sh

### PR DESCRIPTION
**Pull request by marcelpogorzelski**
Created a DisplayLink Manager label

### CODE REVIEW

**Comment by marcelpogorzelski** [comment]
Install Log:
`2022-03-18 09:53:44 : REQ   : displaylinkmanager : ################## Start Installomator v. 9.1beta, date 2022-03-15
2022-03-18 09:53:44 : INFO  : displaylinkmanager : ################## Version: 9.1beta
2022-03-18 09:53:44 : INFO  : displaylinkmanager : ################## Date: 2022-03-15
2022-03-18 09:53:44 : INFO  : displaylinkmanager : ################## displaylinkmanager
2022-03-18 09:53:48 : INFO  : displaylinkmanager : BLOCKING_PROCESS_ACTION=tell_user
2022-03-18 09:53:48 : INFO  : displaylinkmanager : NOTIFY=all
2022-03-18 09:53:48 : INFO  : displaylinkmanager : LOGGING=INFO
2022-03-18 09:53:48 : INFO  : displaylinkmanager : LOGO=/Library/Application Support/JAMF/Jamf.app/Contents/Resources/AppIcon.icns
2022-03-18 09:53:48 : INFO  : displaylinkmanager : Label type: pkg
2022-03-18 09:53:48 : INFO  : displaylinkmanager : archiveName: DisplayLink Manager.pkg
2022-03-18 09:53:48 : INFO  : displaylinkmanager : no blocking processes defined, using DisplayLink Manager as default
2022-03-18 09:53:48 : INFO  : displaylinkmanager : No version found using packageID com.displaylink.displaylinkmanagerapp
2022-03-18 09:53:48 : INFO  : displaylinkmanager : name: DisplayLink Manager, appName: DisplayLink Manager.app
2022-03-18 09:53:48 : INFO  : displaylinkmanager : App(s) found: 
2022-03-18 09:53:48 : WARN  : displaylinkmanager : could not find DisplayLink Manager.app
2022-03-18 09:53:48 : INFO  : displaylinkmanager : appversion: 
2022-03-18 09:53:48 : INFO  : displaylinkmanager : Latest version not specified.
2022-03-18 09:53:48 : REQ   : displaylinkmanager : Downloading https://www.synaptics.com/sites/default/files/exe_files/2022-02/DisplayLink%20Manager%20Graphics%20Connectivity1.6.1-EXE.pkg to DisplayLink Manager.pkg
2022-03-18 09:53:48 : INFO  : displaylinkmanager : notifying
2022-03-18 09:53:52 : REQ   : displaylinkmanager : no more blocking processes, continue with update
2022-03-18 09:53:52 : REQ   : displaylinkmanager : Installing DisplayLink Manager
2022-03-18 09:53:52 : INFO  : displaylinkmanager : notifying
2022-03-18 09:53:52 : INFO  : displaylinkmanager : Verifying: DisplayLink Manager.pkg
2022-03-18 09:53:53 : INFO  : displaylinkmanager : Team ID: 73YQY62QM3 (expected: 73YQY62QM3 )
2022-03-18 09:53:53 : INFO  : displaylinkmanager : Installing DisplayLink Manager.pkg to /
2022-03-18 09:53:56 : INFO  : displaylinkmanager : Finishing...
2022-03-18 09:54:06 : INFO  : displaylinkmanager : found packageID com.displaylink.displaylinkmanagerapp installed, version 5.9.135.0
2022-03-18 09:54:06 : INFO  : displaylinkmanager : Installed DisplayLink Manager, version 5.9.135.0
2022-03-18 09:54:06 : INFO  : displaylinkmanager : notifying
2022-03-18 09:54:07 : INFO  : displaylinkmanager : App not closed, so no reopen.
2022-03-18 09:54:07 : INFO  : displaylinkmanager : 
2022-03-18 09:54:07 : REQ   : displaylinkmanager : ################## End Installomator, exit code 0 `

**Comment by marcelpogorzelski** [comment]
Update Log:
`2022-03-18 09:51:09 : REQ   : displaylinkmanager : ################## Start Installomator v. 9.1beta, date 2022-03-15
2022-03-18 09:51:09 : INFO  : displaylinkmanager : ################## Version: 9.1beta
2022-03-18 09:51:09 : INFO  : displaylinkmanager : ################## Date: 2022-03-15
2022-03-18 09:51:09 : INFO  : displaylinkmanager : ################## displaylinkmanager
2022-03-18 09:51:12 : INFO  : displaylinkmanager : BLOCKING_PROCESS_ACTION=tell_user
2022-03-18 09:51:12 : INFO  : displaylinkmanager : NOTIFY=all
2022-03-18 09:51:12 : INFO  : displaylinkmanager : LOGGING=INFO
2022-03-18 09:51:12 : INFO  : displaylinkmanager : LOGO=/Library/Application Support/JAMF/Jamf.app/Contents/Resources/AppIcon.icns
2022-03-18 09:51:12 : INFO  : displaylinkmanager : Label type: pkg
2022-03-18 09:51:12 : INFO  : displaylinkmanager : archiveName: DisplayLink Manager.pkg
2022-03-18 09:51:12 : INFO  : displaylinkmanager : no blocking processes defined, using DisplayLink Manager as default
2022-03-18 09:51:12 : INFO  : displaylinkmanager : found packageID com.displaylink.displaylinkmanagerapp installed, version 	<string>1.5.0 (125)</string>
2022-03-18 09:51:12 : INFO  : displaylinkmanager : appversion: 	<string>1.5.0 (125)</string>
2022-03-18 09:51:12 : INFO  : displaylinkmanager : Latest version not specified.
2022-03-18 09:51:12 : REQ   : displaylinkmanager : Downloading https://www.synaptics.com/sites/default/files/exe_files/2022-02/DisplayLink%20Manager%20Graphics%20Connectivity1.6.1-EXE.pkg to DisplayLink Manager.pkg
2022-03-18 09:51:12 : INFO  : displaylinkmanager : notifying
2022-03-18 09:51:16 : REQ   : displaylinkmanager : no more blocking processes, continue with update
2022-03-18 09:51:16 : REQ   : displaylinkmanager : Installing DisplayLink Manager
2022-03-18 09:51:16 : INFO  : displaylinkmanager : notifying
2022-03-18 09:51:17 : INFO  : displaylinkmanager : Verifying: DisplayLink Manager.pkg
2022-03-18 09:51:17 : INFO  : displaylinkmanager : Team ID: 73YQY62QM3 (expected: 73YQY62QM3 )
2022-03-18 09:51:17 : INFO  : displaylinkmanager : Checking package version.
2022-03-18 09:51:17 : INFO  : displaylinkmanager : Downloaded package com.displaylink.displaylinkmanagerapp version 5.9.135.0
2022-03-18 09:51:17 : INFO  : displaylinkmanager : Installing DisplayLink Manager.pkg to /
2022-03-18 09:51:21 : INFO  : displaylinkmanager : Finishing...
2022-03-18 09:51:31 : INFO  : displaylinkmanager : found packageID com.displaylink.displaylinkmanagerapp installed, version 5.9.135.0
2022-03-18 09:51:31 : INFO  : displaylinkmanager : Installed DisplayLink Manager, version 5.9.135.0
2022-03-18 09:51:31 : INFO  : displaylinkmanager : notifying
2022-03-18 09:51:31 : INFO  : displaylinkmanager : App not closed, so no reopen.
2022-03-18 09:51:31 : INFO  : displaylinkmanager : 
2022-03-18 09:51:31 : REQ   : displaylinkmanager : ################## End Installomator, exit code 0 `

**Comment by marcelpogorzelski** [comment]
No new version to install Log:
`2022-03-18 09:52:20 : REQ   : displaylinkmanager : ################## Start Installomator v. 9.1beta, date 2022-03-15
2022-03-18 09:52:20 : INFO  : displaylinkmanager : ################## Version: 9.1beta
2022-03-18 09:52:20 : INFO  : displaylinkmanager : ################## Date: 2022-03-15
2022-03-18 09:52:20 : INFO  : displaylinkmanager : ################## displaylinkmanager
2022-03-18 09:52:23 : INFO  : displaylinkmanager : BLOCKING_PROCESS_ACTION=tell_user
2022-03-18 09:52:23 : INFO  : displaylinkmanager : NOTIFY=all
2022-03-18 09:52:23 : INFO  : displaylinkmanager : LOGGING=INFO
2022-03-18 09:52:23 : INFO  : displaylinkmanager : LOGO=/Library/Application Support/JAMF/Jamf.app/Contents/Resources/AppIcon.icns
2022-03-18 09:52:23 : INFO  : displaylinkmanager : Label type: pkg
2022-03-18 09:52:23 : INFO  : displaylinkmanager : archiveName: DisplayLink Manager.pkg
2022-03-18 09:52:23 : INFO  : displaylinkmanager : no blocking processes defined, using DisplayLink Manager as default
2022-03-18 09:52:23 : INFO  : displaylinkmanager : found packageID com.displaylink.displaylinkmanagerapp installed, version 5.9.135.0
2022-03-18 09:52:23 : INFO  : displaylinkmanager : appversion: 5.9.135.0
2022-03-18 09:52:23 : INFO  : displaylinkmanager : Latest version not specified.
2022-03-18 09:52:23 : REQ   : displaylinkmanager : Downloading https://www.synaptics.com/sites/default/files/exe_files/2022-02/DisplayLink%20Manager%20Graphics%20Connectivity1.6.1-EXE.pkg to DisplayLink Manager.pkg
2022-03-18 09:52:23 : INFO  : displaylinkmanager : notifying
2022-03-18 09:52:27 : REQ   : displaylinkmanager : no more blocking processes, continue with update
2022-03-18 09:52:27 : REQ   : displaylinkmanager : Installing DisplayLink Manager
2022-03-18 09:52:27 : INFO  : displaylinkmanager : notifying
2022-03-18 09:52:28 : INFO  : displaylinkmanager : Verifying: DisplayLink Manager.pkg
2022-03-18 09:52:28 : INFO  : displaylinkmanager : Team ID: 73YQY62QM3 (expected: 73YQY62QM3 )
2022-03-18 09:52:28 : INFO  : displaylinkmanager : Checking package version.
2022-03-18 09:52:28 : INFO  : displaylinkmanager : Downloaded package com.displaylink.displaylinkmanagerapp version 5.9.135.0
2022-03-18 09:52:28 : INFO  : displaylinkmanager : Downloaded version of DisplayLink Manager is the same as installed.
2022-03-18 09:52:28 : INFO  : displaylinkmanager : notifying
2022-03-18 09:52:28 : INFO  : displaylinkmanager : App not closed, so no reopen.
2022-03-18 09:52:28 : WARN  : displaylinkmanager : No new version to install
2022-03-18 09:52:28 : REQ   : displaylinkmanager : ################## End Installomator, exit code 0 `

**Comment by scriptingosx** [comment]
Is there some way to create an `appNewVersion` for this?

**Comment by marcelpogorzelski** [comment]
Added `appNewVersion`
Here is the log:
`2022-03-18 15:42:37 : REQ   : displaylinkmanager : ################## Start Installomator v. 9.1beta, date 2022-03-18
2022-03-18 15:42:37 : INFO  : displaylinkmanager : ################## Version: 9.1beta
2022-03-18 15:42:37 : INFO  : displaylinkmanager : ################## Date: 2022-03-18
2022-03-18 15:42:37 : INFO  : displaylinkmanager : ################## displaylinkmanager
2022-03-18 15:43:24 : INFO  : displaylinkmanager : BLOCKING_PROCESS_ACTION=tell_user
2022-03-18 15:43:24 : INFO  : displaylinkmanager : NOTIFY=all
2022-03-18 15:43:24 : INFO  : displaylinkmanager : LOGGING=INFO
2022-03-18 15:43:25 : INFO  : displaylinkmanager : LOGO=/Library/Application Support/JAMF/Jamf.app/Contents/Resources/AppIcon.icns
2022-03-18 15:43:25 : INFO  : displaylinkmanager : Label type: pkg
2022-03-18 15:43:25 : INFO  : displaylinkmanager : archiveName: DisplayLink Manager.pkg
2022-03-18 15:43:25 : INFO  : displaylinkmanager : no blocking processes defined, using DisplayLink Manager as default
2022-03-18 15:43:25 : INFO  : displaylinkmanager : App(s) found: /Applications/DisplayLink Manager.app
2022-03-18 15:43:25 : INFO  : displaylinkmanager : found app at /Applications/DisplayLink Manager.app, version 1.6.1, on versionKey CFBundleShortVersionString
2022-03-18 15:43:25 : INFO  : displaylinkmanager : appversion: 1.6.1
2022-03-18 15:43:25 : INFO  : displaylinkmanager : Latest version of DisplayLink Manager is 1.6.1
2022-03-18 15:43:25 : INFO  : displaylinkmanager : There is no newer version available.
2022-03-18 15:43:25 : INFO  : displaylinkmanager : notifying
2022-03-18 15:43:25 : INFO  : displaylinkmanager : App not closed, so no reopen.
2022-03-18 15:43:25 : WARN  : displaylinkmanager : No newer version.
2022-03-18 15:43:25 : REQ   : displaylinkmanager : ################## End Installomator, exit code 0 `

**Comment by scriptingosx** [comment]
Thanks!

**Pull request merged**
