### PR TITLE
Create protonvpn.sh

### PR DESCRIPTION
**Pull request by fleish**
This adds protonvpn to Installomator

### CODE REVIEW

**Comment by Theile** [comment]
No version to be found?

**Comment by fleish** [comment]
This might work, unless it needs to be strictly numbers & periods: `echo $downloadURL | awk -F\_ '{print $3}' | awk -F\. '{print $1"."$2"."$3}'`

**Comment by Theile** [comment]
It would have to match the content of the field "CFBundleShortVersionString" in Info.plist or another field that you specify. So the "v" does not match. I can fix this, but you get a much better working installation, if you make sure to include this.

**Comment by Theile** [comment]
Now it works:
```
% /Users/st/Documents/GitHub/Installomator/utils/assemble.sh protonvpn
2021-11-24 10:07:19 protonvpn ################## Start Installomator v. 0.8.0
2021-11-24 10:07:19 protonvpn ################## protonvpn
2021-11-24 10:07:19 protonvpn DEBUG mode 1 enabled.
2021-11-24 10:07:20 protonvpn BLOCKING_PROCESS_ACTION=tell_user
2021-11-24 10:07:20 protonvpn NOTIFY=success
2021-11-24 10:07:20 protonvpn LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2021-11-24 10:07:20 protonvpn no blocking processes defined, using ProtonVPN as default
2021-11-24 10:07:20 protonvpn Changing directory to /Users/st/Documents/GitHub/Installomator/build
2021-11-24 10:07:21 protonvpn App(s) found: 
2021-11-24 10:07:21 protonvpn could not find ProtonVPN.app
2021-11-24 10:07:21 protonvpn appversion: 
2021-11-24 10:07:21 protonvpn Latest version of ProtonVPN is 1.9.3
2021-11-24 10:07:21 protonvpn Downloading https://download.protonvpn.net/download/ProtonVPN_mac_v1.9.3.dmg to ProtonVPN.dmg
2021-11-24 10:07:24 protonvpn DEBUG mode, not checking for blocking processes
2021-11-24 10:07:24 protonvpn Installing ProtonVPN
2021-11-24 10:07:24 protonvpn Mounting /Users/st/Documents/GitHub/Installomator/build/ProtonVPN.dmg
2021-11-24 10:07:27 protonvpn Mounted: /Volumes/ProtonVPN
2021-11-24 10:07:27 protonvpn Verifying: /Volumes/ProtonVPN/ProtonVPN.app
2021-11-24 10:07:31 protonvpn Team ID matching: J6S6Q257EK (expected: J6S6Q257EK )
2021-11-24 10:07:32 protonvpn Downloaded version of ProtonVPN is 1.9.3 (replacing version ).
2021-11-24 10:07:32 protonvpn DEBUG enabled, skipping remove, copy and chown steps
2021-11-24 10:07:32 protonvpn Finishing…
2021-11-24 10:07:42 protonvpn App(s) found: 
2021-11-24 10:07:42 protonvpn could not find ProtonVPN.app
2021-11-24 10:07:42 protonvpn Installed ProtonVPN
2021-11-24 10:07:42 protonvpn notifying
2021-11-24 10:07:42 protonvpn Unmounting /Volumes/ProtonVPN
"disk5" ejected.
2021-11-24 10:07:42 protonvpn DEBUG mode, not reopening anything
2021-11-24 10:07:42 protonvpn ################## End Installomator, exit code 0 
```

I do anticipate that the app will ask for permission to install som Launch items, but I haven't tested that.

**Pull request merged**
