### PR TITLE
added BambuStudio and PrusaSlicer

### PR DESCRIPTION
**Pull request by robotprom**
added BambuStudio and PrusaSlicer

### CODE REVIEW

**Comment by scriptingosx** [comment]
Getting an error on `bambustudio`

```
2023-10-13 16:56:55 : REQ   : bambustudio : ################## Start Installomator v. 10.5beta, date 2023-10-13
2023-10-13 16:56:55 : INFO  : bambustudio : ################## Version: 10.5beta
2023-10-13 16:56:55 : INFO  : bambustudio : ################## Date: 2023-10-13
2023-10-13 16:56:55 : INFO  : bambustudio : ################## bambustudio
2023-10-13 16:56:55 : DEBUG : bambustudio : DEBUG mode 1 enabled.
2023-10-13 16:56:56 : DEBUG : bambustudio : name=BambuStudio
2023-10-13 16:56:56 : DEBUG : bambustudio : appName=
2023-10-13 16:56:56 : DEBUG : bambustudio : type=dmg
2023-10-13 16:56:56 : DEBUG : bambustudio : archiveName=
2023-10-13 16:56:56 : DEBUG : bambustudio : downloadURL=https://public-cdn.bambulab.com/upgrade/studio/software/[0-9.]*/Bambu_Studio_mac-v[0-9.]*.dmg
2023-10-13 16:56:56 : DEBUG : bambustudio : curlOptions=
2023-10-13 16:56:56 : DEBUG : bambustudio : appNewVersion=
2023-10-13 16:56:56 : DEBUG : bambustudio : appCustomVersion function: Not defined
2023-10-13 16:56:56 : DEBUG : bambustudio : versionKey=CFBundleShortVersionString
2023-10-13 16:56:56 : DEBUG : bambustudio : packageID=
2023-10-13 16:56:56 : DEBUG : bambustudio : pkgName=
2023-10-13 16:56:56 : DEBUG : bambustudio : choiceChangesXML=
2023-10-13 16:56:56 : DEBUG : bambustudio : expectedTeamID=F4SKHPXDD9
2023-10-13 16:56:56 : DEBUG : bambustudio : blockingProcesses=
2023-10-13 16:56:56 : DEBUG : bambustudio : installerTool=
2023-10-13 16:56:56 : DEBUG : bambustudio : CLIInstaller=
2023-10-13 16:56:56 : DEBUG : bambustudio : CLIArguments=
2023-10-13 16:56:56 : DEBUG : bambustudio : updateTool=
2023-10-13 16:56:56 : DEBUG : bambustudio : updateToolArguments=
2023-10-13 16:56:56 : DEBUG : bambustudio : updateToolRunAsCurrentUser=
2023-10-13 16:56:56 : INFO  : bambustudio : BLOCKING_PROCESS_ACTION=tell_user
2023-10-13 16:56:56 : INFO  : bambustudio : NOTIFY=success
2023-10-13 16:56:56 : INFO  : bambustudio : LOGGING=DEBUG
2023-10-13 16:56:56 : INFO  : bambustudio : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2023-10-13 16:56:56 : INFO  : bambustudio : Label type: dmg
2023-10-13 16:56:56 : INFO  : bambustudio : archiveName: BambuStudio.dmg
2023-10-13 16:56:56 : INFO  : bambustudio : no blocking processes defined, using BambuStudio as default
2023-10-13 16:56:56 : DEBUG : bambustudio : Changing directory to /Users/armin/BTSync/Work/Projects/Installomator/build
2023-10-13 16:56:56 : INFO  : bambustudio : name: BambuStudio, appName: BambuStudio.app
2023-10-13 16:56:56.124 mdfind[475:6169273] [UserQueryParser] Loading keywords and predicates for locale "en_US"
2023-10-13 16:56:56.125 mdfind[475:6169273] [UserQueryParser] Loading keywords and predicates for locale "en"
2023-10-13 16:56:56.168 mdfind[475:6169273] Couldn't determine the mapping between prefab keywords and predicates.
2023-10-13 16:56:56 : WARN  : bambustudio : No previous app found
2023-10-13 16:56:56 : WARN  : bambustudio : could not find BambuStudio.app
2023-10-13 16:56:56 : INFO  : bambustudio : appversion: 
2023-10-13 16:56:56 : INFO  : bambustudio : Latest version not specified.
2023-10-13 16:56:56 : REQ   : bambustudio : Downloading https://public-cdn.bambulab.com/upgrade/studio/software/[0-9.]*/Bambu_Studio_mac-v[0-9.]*.dmg to BambuStudio.dmg
2023-10-13 16:56:56 : DEBUG : bambustudio : No Dialog connection, just download
2023-10-13 16:56:56 : ERROR : bambustudio : error downloading https://public-cdn.bambulab.com/upgrade/studio/software/[0-9.]*/Bambu_Studio_mac-v[0-9.]*.dmg
ls: BambuStudio.dmg: No such file or directory
2023-10-13 16:56:56 : ERROR : bambustudio : File list: 
2023-10-13 16:56:56 : ERROR : bambustudio : File type: BambuStudio.dmg: cannot open `BambuStudio.dmg' (No such file or directory)
2023-10-13 16:56:56 : DEBUG : bambustudio : DEBUG mode 1, not reopening anything
2023-10-13 16:56:56 : ERROR : bambustudio : ERROR: Error downloading https://public-cdn.bambulab.com/upgrade/studio/software/[0-9.]*/Bambu_Studio_mac-v[0-9.]*.dmg error:
curl: (3) bad range in URL position 60:
https://public-cdn.bambulab.com/upgrade/studio/software/[0-9.]*/Bambu_Studio_mac-v[0-9.]*.dmg
^

2023-10-13 16:56:56 : REQ   : bambustudio : ################## End Installomator, exit code 2 

something went wrong, stopping here
exit code: 0
```

**Comment by scriptingosx** [comment]
Note: `prusaslicer` is working fine. If you had put those in as separate PRs, I could have merged that. Now it has to wait...

**Comment by robotprom** [comment]
I will go back and resubmit them as individual pulls. I think Bambu changed
their naming syntax as I’m now getting errors when I test it.

**Comment by robotprom** [comment]
separate branches: 

prusaslicer: https://github.com/Installomator/Installomator/pull/1259

Bambu Studio: https://github.com/Installomator/Installomator/pull/1260

**Comment by scriptingosx** [comment]
thank you, closing this as duplicate now

**Pull request closed without merging**
