### PR TITLE
New Label: Eclipse Temurin 8

### PR DESCRIPTION
**Pull request by kryptonit1**
2024-01-23 09:26:11 : REQ   : eclipsetemurin8 : ################## Start Installomator v. 10.6beta, date 2024-01-23
2024-01-23 09:26:11 : INFO  : eclipsetemurin8 : ################## Version: 10.6beta
2024-01-23 09:26:11 : INFO  : eclipsetemurin8 : ################## Date: 2024-01-23
2024-01-23 09:26:11 : INFO  : eclipsetemurin8 : ################## eclipsetemurin8
2024-01-23 09:26:11 : INFO  : eclipsetemurin8 : SwiftDialog is not installed, clear cmd file var
2024-01-23 09:26:11 : INFO  : eclipsetemurin8 : setting variable from argument DEBUG=0
2024-01-23 09:26:11 : INFO  : eclipsetemurin8 : BLOCKING_PROCESS_ACTION=tell_user
2024-01-23 09:26:11 : INFO  : eclipsetemurin8 : NOTIFY=success
2024-01-23 09:26:11 : INFO  : eclipsetemurin8 : LOGGING=INFO
2024-01-23 09:26:11 : INFO  : eclipsetemurin8 : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2024-01-23 09:26:11 : INFO  : eclipsetemurin8 : Label type: pkg
2024-01-23 09:26:12 : INFO  : eclipsetemurin8 : archiveName: Temurin 8.pkg
2024-01-23 09:26:12 : INFO  : eclipsetemurin8 : no blocking processes defined, using Temurin 8 as default
2024-01-23 09:26:12 : INFO  : eclipsetemurin8 : Custom App Version detection is used, found
2024-01-23 09:26:12 : INFO  : eclipsetemurin8 : appversion:
2024-01-23 09:26:12 : INFO  : eclipsetemurin8 : Latest version of Temurin 8 is 8u402-b06
2024-01-23 09:26:12 : REQ   : eclipsetemurin8 : Downloading https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u402-b06/OpenJDK8U-jdk_x64_mac_hotspot_8u402b06.pkg to Temurin 8.pkg
2024-01-23 09:26:13 : REQ   : eclipsetemurin8 : no more blocking processes, continue with update
2024-01-23 09:26:13 : REQ   : eclipsetemurin8 : Installing Temurin 8
2024-01-23 09:26:13 : INFO  : eclipsetemurin8 : Verifying: Temurin 8.pkg
2024-01-23 09:26:13 : INFO  : eclipsetemurin8 : Team ID: JCDTMS22B4 (expected: JCDTMS22B4 )
2024-01-23 09:26:13 : INFO  : eclipsetemurin8 : Installing Temurin 8.pkg to /
2024-01-23 09:26:32 : INFO  : eclipsetemurin8 : Finishing...
2024-01-23 09:26:35 : INFO  : eclipsetemurin8 : Custom App Version detection is used, found 8u402-b06
2024-01-23 09:26:35 : REQ   : eclipsetemurin8 : Installed Temurin 8, version 8u402-b06
2024-01-23 09:26:35 : INFO  : eclipsetemurin8 : notifying
displaynotification:7: no such file or directory: /usr/local/bin/dialog
2024-01-23 09:26:35 : INFO  : eclipsetemurin8 : Installomator did not close any apps, so no need to reopen any apps.
2024-01-23 09:26:35 : REQ   : eclipsetemurin8 : All done!
2024-01-23 09:26:35 : REQ   : eclipsetemurin8 : ################## End Installomator, exit code 0

### CODE REVIEW

**Comment by BigMacAdmin** [comment]
Thank you!

**Comment by BigMacAdmin** [comment]
These folks really didn't make their versioning easy on us, did they?

**Comment by BigMacAdmin** [comment]
Thank you!

**Comment by kryptonit1** [comment]
> These folks really didn't make their versioning easy on us, did they?

Haha nope, not really 😆.

**Pull request merged**
