### PR TITLE
Added Label etssecurebrowser.sh

### PR DESCRIPTION
**Pull request by robotprom**
ETS secure testing browser

### CODE REVIEW

**Comment by Theile** [comment]
`appNewVersion` is missing, can you fix this, or comment on what the problem is?

**Comment by robotprom** [comment]
it pulls version from the versionKey

**Comment by BigMacAdmin** [comment]
I poked around, and was unable to find any public release notes or version number on their website. I will merge this in.

**Comment by BigMacAdmin** [comment]
Thank you!

**Pull request merged**
