### PR TITLE
Create tower.sh

### PR DESCRIPTION
**Pull request by MacMike077**
2023-03-08 11:40:57 : REQ   : tower : ################## Start Installomator v. 10.3, date 2023-02-10
2023-03-08 11:40:57 : INFO  : tower : ################## Version: 10.3
2023-03-08 11:40:57 : INFO  : tower : ################## Date: 2023-02-10
2023-03-08 11:40:57 : INFO  : tower : ################## tower
2023-03-08 11:40:57 : INFO  : tower : SwiftDialog is not installed, clear cmd file var
2023-03-08 11:40:57 : INFO  : tower : BLOCKING_PROCESS_ACTION=tell_user
2023-03-08 11:40:57 : INFO  : tower : NOTIFY=success
2023-03-08 11:40:57 : INFO  : tower : LOGGING=INFO
2023-03-08 11:40:57 : INFO  : tower : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2023-03-08 11:40:57 : INFO  : tower : Label type: zip
2023-03-08 11:40:57 : INFO  : tower : archiveName: Tower.zip
2023-03-08 11:40:57 : INFO  : tower : no blocking processes defined, using Tower as default
2023-03-08 11:40:57 : INFO  : tower : name: Tower, appName: Tower.app
2023-03-08 11:40:57.754 mdfind[74815:13066630] [UserQueryParser] Loading keywords and predicates for locale "nl_NL"
2023-03-08 11:40:57.754 mdfind[74815:13066630] [UserQueryParser] Loading keywords and predicates for locale "nl"
2023-03-08 11:40:57 : WARN  : tower : No previous app found
2023-03-08 11:40:57 : WARN  : tower : could not find Tower.app
2023-03-08 11:40:57 : INFO  : tower : appversion:
2023-03-08 11:40:57 : INFO  : tower : Latest version not specified.
2023-03-08 11:40:57 : REQ   : tower : Downloading https://www.git-tower.com/download/mac to Tower.zip
2023-03-08 11:41:12 : REQ   : tower : no more blocking processes, continue with update
2023-03-08 11:41:12 : REQ   : tower : Installing Tower
2023-03-08 11:41:12 : INFO  : tower : Unzipping Tower.zip
2023-03-08 11:41:12 : INFO  : tower : Verifying: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.7FUBu3Ky/Tower.app
2023-03-08 11:41:13 : INFO  : tower : Team ID matching: UN97WY764J (expected: UN97WY764J )
2023-03-08 11:41:13 : INFO  : tower : Installing Tower version 9.2 on versionKey CFBundleShortVersionString.
2023-03-08 11:41:13 : INFO  : tower : App has LSMinimumSystemVersion: 10.15
2023-03-08 11:41:13 : INFO  : tower : Copy /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.7FUBu3Ky/Tower.app to /Applications
2023-03-08 11:41:13 : WARN  : tower : Changing owner to maikelwork
2023-03-08 11:41:13 : INFO  : tower : Finishing...
2023-03-08 11:41:16 : INFO  : tower : App(s) found: /Applications/Tower.app
2023-03-08 11:41:16 : INFO  : tower : found app at /Applications/Tower.app, version 9.2, on versionKey CFBundleShortVersionString
2023-03-08 11:41:16 : REQ   : tower : Installed Tower, version 9.2
2023-03-08 11:41:16 : INFO  : tower : notifying
2023-03-08 11:41:16 : INFO  : tower : App not closed, so no reopen.
2023-03-08 11:41:16 : REQ   : tower : All done!
2023-03-08 11:41:16 : REQ   : tower : ################## End Installomator, exit code 0

### CODE REVIEW

**Comment by MacMike077** [comment]
This label does not check for versioning before downloading.
When this is required, I need some help with this.

**Comment by asri-tm** [comment]
the actual download URL seems to be https://www.git-tower.com/updates/tower3-mac/stable/releases/latest/download
And with that you can get release information @ https://www.git-tower.com/updates/tower3-mac/stable/releases

**Comment by MacMike077** [comment]
@asri-tm, great follow up. I'm gonna check this and change the PR

**Comment by scriptingosx** [comment]
Thank you!

**Pull request merged**
