### PR TITLE
Add Zoom Rooms

### PR DESCRIPTION
**Pull request by mattdjerome**
zoomroom)
    name="Zoom Room"
    type="pkg"
    downloadURL="https://zoom.us/client/latest/ZoomRooms.pkg"
    expectedTeamID="BJ4HAAB9B3"
    ;;

### CODE REVIEW

**Comment by Theile** [comment]
This PR looks like a mess. I don't think we can add that. ZoomRoom is not even part of the changes in the files.

**Comment by mattdjerome** [comment]
How can I make it better in the future? I've never done this before.

**Comment by Theile** [comment]
I didn't wanted to complain to you, but this PR looks like it has a long history of changes, but the name of this PR is Zoom Room. And when I go to "Files changed", and look at Installomator.sh, to see what changes are there, there is no zoomroom label in it.

So I can see your comment with zoomroom, but the comment should be a description of what has changed, and the changes should be part of the "Files changed" section, where the files are directly changed.

My "mess"-description was about the long list of changes that has happened to this PR, not really to criticise that you wrote a text in the wrong place, sorry for that. I have asked the other participant for what has been going on with this PR history wise.

I usually go directly to the file I want to change, click on the modify button, and apply my changes in a PR, maybe some easier way exist, as I don't think I'm an expert in this GitHub-thing yet. But take a look at my PR for zoomroom, and look at the changes.

Thanks for your participation!

**Comment by acodega** [comment]
Hi mattdjerome, I'm going to close this pull request. I think you opened a PR of the dev branch into the labels branch which was a mistake. We can go over it more on Slack sometime, and we're planning a blog post soon to help people get started with contributing on GitHub. For now I'm going to close it out since it was done in error.

**Pull request closed without merging**
