### PR TITLE
Update Installomator.sh

### PR DESCRIPTION
**Pull request by YanirTest**
jdk21)
    name="Java SE Development Kit 21"
    type="pkgInDmg"
    versionKey="CFBundleShortVersionString"
    appNewVersion=$(curl -sf https://www.oracle.com/java/technologies/javase/jdk21-archive-downloads.html | grep -m 1 "Java SE Development Kit" | sed "s|.*Kit \(.*\)\<.*|\\1|")
    if [[ $(arch) == "arm64" ]]; then
        downloadURL="https://download.oracle.com/java/21/archive/jdk-"$appNewVersion"_macos-aarch64_bin.dmg"
    elif [[ $(arch) == "i386" ]]; then
        downloadURL="https://download.oracle.com/java/21/archive/jdk-"$appNewVersion"_macos-x64_bin.dmg"
    fi
    appCustomVersion(){ java --version | grep java | awk '{print $2}' }
    expectedTeamID="VB5E2TV963"

### CODE REVIEW

**Comment by KMTMark** [comment]
https://github.com/Installomator/Installomator/wiki/Contributing-to-Installomator

Probably gonna need to retract this and do as the Wiki says and submit the PR against the relevant label.

**Comment by rougegoat** [comment]
Just a heads up, you'll want to make the change to the fragment rather than the main script.  The main script is automatically assembled from those fragments, so PRs to it directly would just get overridden the next time it's built.
https://github.com/Installomator/Installomator/wiki/GitHub-howto-create-PRs#make-changes

**Comment by Theile** [comment]
You have to make changes to /fragments/labels/ files, not Installomator.sh. Installomator.sh is automatically generated.

Please fix this.

**Comment by Theile** [comment]
And rename the PR to whatever label you are fixing. Thank you.

**Pull request closed without merging**
