### PR TITLE
Update trapcode.sh - fixed appCustomVersion and appNewVersion

### PR DESCRIPTION
**Pull request by aduffner**
```
sudo /Users/duf0002a/workdir/GitHub/Installomator/assemble.sh trapcode
2024-04-03 17:37:27 : REQ   : trapcode : ################## Start Installomator v. 10.6beta, date 2024-04-03
2024-04-03 17:37:27 : INFO  : trapcode : ################## Version: 10.6beta
2024-04-03 17:37:27 : INFO  : trapcode : ################## Date: 2024-04-03
2024-04-03 17:37:27 : INFO  : trapcode : ################## trapcode
2024-04-03 17:37:27 : DEBUG : trapcode : DEBUG mode 1 enabled.
2024-04-03 17:37:28 : INFO  : trapcode : Had to change DownloadURL due HTTP Status.
2024-04-03 17:37:28 : DEBUG : trapcode : name=Trapcode Suite
2024-04-03 17:37:28 : DEBUG : trapcode : appName=
2024-04-03 17:37:28 : DEBUG : trapcode : type=zip
2024-04-03 17:37:28 : DEBUG : trapcode : archiveName=
2024-04-03 17:37:28 : DEBUG : trapcode : downloadURL=https://mx-app-blob-prod.maxon.net/mx-package-production/installer/macos/redgiant/trapcode/releases/2024.1.0/TrapcodeSuite-2024.1.0_mac.zip
2024-04-03 17:37:28 : DEBUG : trapcode : curlOptions=
2024-04-03 17:37:28 : DEBUG : trapcode : appNewVersion=2024.1.0
2024-04-03 17:37:28 : DEBUG : trapcode : appCustomVersion function: Defined. 
2024-04-03 17:37:28 : DEBUG : trapcode : versionKey=CFBundleShortVersionString
2024-04-03 17:37:28 : DEBUG : trapcode : packageID=
2024-04-03 17:37:28 : DEBUG : trapcode : pkgName=
2024-04-03 17:37:28 : DEBUG : trapcode : choiceChangesXML=
2024-04-03 17:37:28 : DEBUG : trapcode : expectedTeamID=4ZY22YGXQG
2024-04-03 17:37:28 : DEBUG : trapcode : blockingProcesses=
2024-04-03 17:37:28 : DEBUG : trapcode : installerTool=Trapcode Suite Installer.app
2024-04-03 17:37:28 : DEBUG : trapcode : CLIInstaller=Trapcode Suite Installer.app/Contents/MacOS/Trapcode Suite Installer
2024-04-03 17:37:28 : DEBUG : trapcode : CLIArguments=
2024-04-03 17:37:28 : DEBUG : trapcode : updateTool=
2024-04-03 17:37:28 : DEBUG : trapcode : updateToolArguments=
2024-04-03 17:37:28 : DEBUG : trapcode : updateToolRunAsCurrentUser=
2024-04-03 17:37:28 : INFO  : trapcode : BLOCKING_PROCESS_ACTION=tell_user
2024-04-03 17:37:28 : INFO  : trapcode : NOTIFY=success
2024-04-03 17:37:28 : INFO  : trapcode : LOGGING=DEBUG
2024-04-03 17:37:28 : INFO  : trapcode : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2024-04-03 17:37:28 : INFO  : trapcode : Label type: zip
2024-04-03 17:37:28 : INFO  : trapcode : archiveName: Trapcode Suite.zip
2024-04-03 17:37:28 : INFO  : trapcode : no blocking processes defined, using Trapcode Suite as default
2024-04-03 17:37:28 : DEBUG : trapcode : Changing directory to /Users/duf0002a/workdir/GitHub/Installomator/build
2024-04-03 17:37:28 : INFO  : trapcode : Custom App Version detection is used, found 2023.3.1
2024-04-03 17:37:28 : INFO  : trapcode : appversion: 2023.3.1
2024-04-03 17:37:28 : INFO  : trapcode : Latest version of Trapcode Suite is 2024.1.0
2024-04-03 17:37:28 : INFO  : trapcode : Trapcode Suite.zip exists and DEBUG mode 1 enabled, skipping download
2024-04-03 17:37:28 : DEBUG : trapcode : DEBUG mode 1, not checking for blocking processes
2024-04-03 17:37:28 : REQ   : trapcode : Installing Trapcode Suite
2024-04-03 17:37:28 : REQ   : trapcode : installerTool used: Trapcode Suite Installer.app
2024-04-03 17:37:28 : INFO  : trapcode : Unzipping Trapcode Suite.zip
2024-04-03 17:37:29 : INFO  : trapcode : Verifying: /Users/duf0002a/workdir/GitHub/Installomator/build/Trapcode Suite Installer.app
2024-04-03 17:37:29 : DEBUG : trapcode : App size: 982M	/Users/duf0002a/workdir/GitHub/Installomator/build/Trapcode Suite Installer.app
2024-04-03 17:37:30 : DEBUG : trapcode : Debugging enabled, App Verification output was:
/Users/duf0002a/workdir/GitHub/Installomator/build/Trapcode Suite Installer.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: Maxon Computer GmbH (4ZY22YGXQG)

2024-04-03 17:37:30 : INFO  : trapcode : Team ID matching: 4ZY22YGXQG (expected: 4ZY22YGXQG )
2024-04-03 17:37:30 : INFO  : trapcode : Downloaded version of Trapcode Suite is 2024.1.0 on versionKey CFBundleShortVersionString (replacing version 2023.3.1).
2024-04-03 17:37:30 : INFO  : trapcode : App has LSMinimumSystemVersion: 10.11
2024-04-03 17:37:30 : DEBUG : trapcode : DEBUG mode 1 enabled, skipping remove, copy and chown steps
2024-04-03 17:37:30 : INFO  : trapcode : Finishing...
2024-04-03 17:37:33 : INFO  : trapcode : Custom App Version detection is used, found 2023.3.1
2024-04-03 17:37:33 : REQ   : trapcode : Installed Trapcode Suite, version 2024.1.0
2024-04-03 17:37:33 : INFO  : trapcode : notifying
2024-04-03 17:37:33 : DEBUG : trapcode : DEBUG mode 1, not reopening anything
2024-04-03 17:37:33 : REQ   : trapcode : All done!
2024-04-03 17:37:33 : REQ   : trapcode : ################## End Installomator, exit code 0 
```

### CODE REVIEW

**Comment by Theile** [comment]
Looks like it's `appNewVersion` you have changed and not `appCustomVersion()`.

Anyway, I cannot se a result from either `appNewVersion` commands, could you look at them again?

**Comment by aduffner** [comment]
@Theile I changed both, in two commits. How did you get nothing?
```
curl -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15" -fs "https://support.maxon.net/hc/en-us/sections/13336955539228-Red-Giant" | grep -i trapcode | grep -Eo "202[0-9]+\.[0-9]+\.[0-9]+" | sort -gru | head -n 1
```
Result: `2024.1.0`

**Comment by Theile** [comment]
OK, I honestly got nothing returned before. Thanks for responding quick!

**Comment by BigMacAdmin** [comment]
It appears that this may be an unreliable label, or that the vendor's site is unreliable. I am also getting no value from `appNewVersion` (the old one and the new one come out blank.)

The very first command in the pipe is coming out empty for me when I try outside of the script. When I run our testpr script, `appNewVersion` is coming out empty. 

Since `appNewVersion` is coming up blank, I am also got a download error (because `downloadURL` requires that value)

```
./utils/test-pr.sh 1575 trapcode
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 15 (delta 9), reused 9 (delta 8), pack-reused 0
Unpacking objects: 100% (15/15), 3.89 KiB | 234.00 KiB/s, done.
From https://github.com/Installomator/Installomator
 * [new ref]         refs/pull/1575/head -> pr/1575
Switched to branch 'pr/1575'
2024-04-23 22:16:40 : REQ   : trapcode : ################## Start Installomator v. 10.6beta, date 2024-04-23
2024-04-23 22:16:40 : INFO  : trapcode : ################## Version: 10.6beta
2024-04-23 22:16:40 : INFO  : trapcode : ################## Date: 2024-04-23
2024-04-23 22:16:40 : INFO  : trapcode : ################## trapcode
2024-04-23 22:16:40 : DEBUG : trapcode : DEBUG mode 1 enabled.
2024-04-23 22:16:41 : INFO  : trapcode : Had to change DownloadURL due HTTP Status.
2024-04-23 22:16:41 : DEBUG : trapcode : name=Trapcode Suite
2024-04-23 22:16:41 : DEBUG : trapcode : appName=
2024-04-23 22:16:41 : DEBUG : trapcode : type=zip
2024-04-23 22:16:41 : DEBUG : trapcode : archiveName=
2024-04-23 22:16:41 : DEBUG : trapcode : downloadURL=https://mx-app-blob-prod.maxon.net/mx-package-production/installer/macos/redgiant/trapcode/releases//TrapcodeSuite-_mac.zip
2024-04-23 22:16:41 : DEBUG : trapcode : curlOptions=
2024-04-23 22:16:41 : DEBUG : trapcode : appNewVersion=
2024-04-23 22:16:41 : DEBUG : trapcode : appCustomVersion function: Defined. 
2024-04-23 22:16:41 : DEBUG : trapcode : versionKey=CFBundleShortVersionString
2024-04-23 22:16:41 : DEBUG : trapcode : packageID=
2024-04-23 22:16:41 : DEBUG : trapcode : pkgName=
2024-04-23 22:16:41 : DEBUG : trapcode : choiceChangesXML=
2024-04-23 22:16:41 : DEBUG : trapcode : expectedTeamID=4ZY22YGXQG
2024-04-23 22:16:41 : DEBUG : trapcode : blockingProcesses=
2024-04-23 22:16:41 : DEBUG : trapcode : installerTool=Trapcode Suite Installer.app
2024-04-23 22:16:41 : DEBUG : trapcode : CLIInstaller=Trapcode Suite Installer.app/Contents/MacOS/Trapcode Suite Installer
2024-04-23 22:16:41 : DEBUG : trapcode : CLIArguments=
2024-04-23 22:16:41 : DEBUG : trapcode : updateTool=
2024-04-23 22:16:41 : DEBUG : trapcode : updateToolArguments=
2024-04-23 22:16:41 : DEBUG : trapcode : updateToolRunAsCurrentUser=
2024-04-23 22:16:41 : INFO  : trapcode : BLOCKING_PROCESS_ACTION=tell_user
2024-04-23 22:16:41 : INFO  : trapcode : NOTIFY=success
2024-04-23 22:16:41 : INFO  : trapcode : LOGGING=DEBUG
2024-04-23 22:16:41 : INFO  : trapcode : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2024-04-23 22:16:41 : INFO  : trapcode : Label type: zip
2024-04-23 22:16:41 : INFO  : trapcode : archiveName: Trapcode Suite.zip
2024-04-23 22:16:41 : INFO  : trapcode : no blocking processes defined, using Trapcode Suite as default
2024-04-23 22:16:41 : DEBUG : trapcode : Changing directory to /Users/bigmacadmin/Documents/GitHub/installomator/build
ls: /Users/Shared/Red Giant/uninstall: No such file or directory
2024-04-23 22:16:41 : INFO  : trapcode : Custom App Version detection is used, found 
2024-04-23 22:16:41 : INFO  : trapcode : appversion: 
2024-04-23 22:16:41 : INFO  : trapcode : Latest version not specified.
2024-04-23 22:16:41 : REQ   : trapcode : Downloading https://mx-app-blob-prod.maxon.net/mx-package-production/installer/macos/redgiant/trapcode/releases//TrapcodeSuite-_mac.zip to Trapcode Suite.zip
2024-04-23 22:16:41 : DEBUG : trapcode : No Dialog connection, just download
2024-04-23 22:16:42 : ERROR : trapcode : error downloading https://mx-app-blob-prod.maxon.net/mx-package-production/installer/macos/redgiant/trapcode/releases//TrapcodeSuite-_mac.zip
```

**Comment by meysq** [comment]
This can be used to fix all Maxon apps besides Trapcode, btw - applied this fix to Magic Bullet and it did work.

**Comment by aduffner** [comment]
Yes, that's why I also edited the other maxon related labels 😄

**Pull request merged**
