### PR TITLE
Add label CrashplanSMB 

### PR DESCRIPTION
**Pull request by jnichols35**
~/Documents/Dev/Installomator/build   label-crashplan  sudo ./Installomator.sh crashplansmb DEBUG=0
2023-03-02 11:53:50 : INFO  : crashplansmb : setting variable from argument DEBUG=0
2023-03-02 11:53:50 : REQ   : crashplansmb : ################## Start Installomator v. 10.4beta, date 2023-03-02
2023-03-02 11:53:50 : INFO  : crashplansmb : ################## Version: 10.4beta
2023-03-02 11:53:50 : INFO  : crashplansmb : ################## Date: 2023-03-02
2023-03-02 11:53:50 : INFO  : crashplansmb : ################## crashplansmb
2023-03-02 11:53:50 : INFO  : crashplansmb : SwiftDialog is not installed, clear cmd file var
2023-03-02 11:53:50 : INFO  : crashplansmb : BLOCKING_PROCESS_ACTION=tell_user
2023-03-02 11:53:50 : INFO  : crashplansmb : NOTIFY=success
2023-03-02 11:53:50 : INFO  : crashplansmb : LOGGING=INFO
2023-03-02 11:53:50 : INFO  : crashplansmb : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2023-03-02 11:53:50 : INFO  : crashplansmb : Label type: pkgInDmg
2023-03-02 11:53:50 : INFO  : crashplansmb : archiveName: Code42.dmg
2023-03-02 11:53:50 : INFO  : crashplansmb : no blocking processes defined, using Code42 as default
2023-03-02 11:53:50 : INFO  : crashplansmb : name: Code42, appName: Code42.app
2023-03-02 11:53:50.711 mdfind[54972:5058620] [UserQueryParser] Loading keywords and predicates for locale "en_US"
2023-03-02 11:53:50.711 mdfind[54972:5058620] [UserQueryParser] Loading keywords and predicates for locale "en"
2023-03-02 11:53:50.830 mdfind[54972:5058620] Couldn't determine the mapping between prefab keywords and predicates.
2023-03-02 11:53:50 : WARN  : crashplansmb : No previous app found
2023-03-02 11:53:50 : WARN  : crashplansmb : could not find Code42.app
2023-03-02 11:53:50 : INFO  : crashplansmb : appversion:
2023-03-02 11:53:50 : INFO  : crashplansmb : Latest version not specified.
2023-03-02 11:53:50 : REQ   : crashplansmb : Downloading https://download.crashplan.com/installs/agent/latest-smb-mac.dmg to Code42.dmg
2023-03-02 11:53:57 : REQ   : crashplansmb : no more blocking processes, continue with update
2023-03-02 11:53:57 : REQ   : crashplansmb : Installing Code42
2023-03-02 11:53:57 : INFO  : crashplansmb : Mounting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.PRfE5S9k/Code42.dmg
2023-03-02 11:54:00 : INFO  : crashplansmb : Mounted: /Volumes/CrashPlanSmb 1
2023-03-02 11:54:00 : INFO  : crashplansmb : found pkg: /Volumes/CrashPlanSmb 1/Install Crashplan for SMall Business.pkg
2023-03-02 11:54:00 : INFO  : crashplansmb : Verifying: /Volumes/CrashPlanSmb 1/Install Crashplan for SMall Business.pkg
2023-03-02 11:54:00 : INFO  : crashplansmb : Team ID: 9YV9435DHD (expected: 9YV9435DHD )
2023-03-02 11:54:00 : INFO  : crashplansmb : Installing /Volumes/CrashPlanSmb 1/Install Crashplan for SMall Business.pkg to /
2023-03-02 11:54:32 : INFO  : crashplansmb : Finishing...
2023-03-02 11:54:35 : INFO  : crashplansmb : App(s) found: /Applications/Code42.app
2023-03-02 11:54:36 : INFO  : crashplansmb : found app at /Applications/Code42.app, version 10.4.1, on versionKey CFBundleShortVersionString
2023-03-02 11:54:36 : REQ   : crashplansmb : Installed Code42, version 10.4.1
2023-03-02 11:54:36 : INFO  : crashplansmb : notifying
2023-03-02 11:54:37 : INFO  : crashplansmb : App not closed, so no reopen.
2023-03-02 11:54:37 : REQ   : crashplansmb : All done!
2023-03-02 11:54:37 : REQ   : crashplansmb : ################## End Installomator, exit code 0

### CODE REVIEW

**Comment by orrison-CrashPlan** [comment]
As of just a couple weeks ago there are some changes that need to be made here to make this accurate.

The Name should be `CrashPlan`, and teamID `UGHXR79U6M`

As of March 16 the latest link downloads version 11.0.1 which has these values.

```
name="CrashPlan"
expectedTeamID="UGHXR79U6M"
```

**Comment by apizz** [comment]
Don't believe as written is accurate.  Here's what I've gathered:

```
CrashPlan)
    name="CrashPlan"
    type="pkgInDmg"
    pkgName="Install CrashPlan.pkg"
    downloadURL="https://download.crashplan.com/installs/agent/latest-mac.dmg"
    expectedTeamID="UGHXR79U6M"
    blockingProcesses=( NONE )
    ;;
```
Screenshot 2023-03-23 at 1 40 02 PM

**Comment by jnichols35** [comment]
Based on @orrison-CrashPlan comment, I updated the label once again. 

> ❯ sudo ./Installomator.sh crashplansmb DEBUG=0
> 2023-03-24 10:53:14 : INFO  : crashplansmb : setting variable from argument DEBUG=0
> 2023-03-24 10:53:14 : REQ   : crashplansmb : ################## Start Installomator v. 10.4beta, date 2023-03-24
> 2023-03-24 10:53:14 : INFO  : crashplansmb : ################## Version: 10.4beta
> 2023-03-24 10:53:14 : INFO  : crashplansmb : ################## Date: 2023-03-24
> 2023-03-24 10:53:14 : INFO  : crashplansmb : ################## crashplansmb
> 2023-03-24 10:53:14 : INFO  : crashplansmb : SwiftDialog is not installed, clear cmd file var
> 2023-03-24 10:53:14 : INFO  : crashplansmb : BLOCKING_PROCESS_ACTION=tell_user
> 2023-03-24 10:53:14 : INFO  : crashplansmb : NOTIFY=success
> 2023-03-24 10:53:14 : INFO  : crashplansmb : LOGGING=INFO
> 2023-03-24 10:53:14 : INFO  : crashplansmb : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
> 2023-03-24 10:53:14 : INFO  : crashplansmb : Label type: pkgInDmg
> 2023-03-24 10:53:14 : INFO  : crashplansmb : archiveName: CrashPlan.dmg
> 2023-03-24 10:53:14 : INFO  : crashplansmb : name: CrashPlan, appName: CrashPlan.app
> 2023-03-24 10:53:14.735 mdfind[53441:564528] [UserQueryParser] Loading keywords and predicates for locale "en_US"
> 2023-03-24 10:53:14.735 mdfind[53441:564528] [UserQueryParser] Loading keywords and predicates for locale "en"
> 2023-03-24 10:53:14.881 mdfind[53441:564528] Couldn't determine the mapping between prefab keywords and predicates.
> 2023-03-24 10:53:14 : WARN  : crashplansmb : No previous app found
> 2023-03-24 10:53:14 : WARN  : crashplansmb : could not find CrashPlan.app
> 2023-03-24 10:53:14 : INFO  : crashplansmb : appversion:
> 2023-03-24 10:53:14 : INFO  : crashplansmb : Latest version not specified.
> 2023-03-24 10:53:14 : REQ   : crashplansmb : Downloading https://download.crashplan.com/installs/agent/latest-smb-mac.dmg to CrashPlan.dmg
> 2023-03-24 10:53:21 : REQ   : crashplansmb : Installing CrashPlan
> 2023-03-24 10:53:21 : INFO  : crashplansmb : Mounting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.55K0rXNc/CrashPlan.dmg
> 2023-03-24 10:53:24 : INFO  : crashplansmb : Mounted: /Volumes/CrashPlanSmb 1
> 2023-03-24 10:53:24 : INFO  : crashplansmb : found pkg: /Volumes/CrashPlanSmb 1/Install Crashplan.pkg
> 2023-03-24 10:53:24 : INFO  : crashplansmb : Verifying: /Volumes/CrashPlanSmb 1/Install Crashplan.pkg
> 2023-03-24 10:53:24 : INFO  : crashplansmb : Team ID: UGHXR79U6M (expected: UGHXR79U6M )
> 2023-03-24 10:53:24 : INFO  : crashplansmb : Installing /Volumes/CrashPlanSmb 1/Install Crashplan.pkg to /
> 2023-03-24 10:53:54 : INFO  : crashplansmb : Finishing...
> 2023-03-24 10:53:57 : INFO  : crashplansmb : App(s) found: /Applications/CrashPlan.app
> 2023-03-24 10:53:57 : INFO  : crashplansmb : found app at /Applications/CrashPlan.app, version 11.0.1, on versionKey CFBundleShortVersionString
> 2023-03-24 10:53:57 : REQ   : crashplansmb : Installed CrashPlan, version 11.0.1
> 2023-03-24 10:53:57 : INFO  : crashplansmb : notifying
> 2023-03-24 10:53:58 : INFO  : crashplansmb : App not closed, so no reopen.
> 2023-03-24 10:53:58 : REQ   : crashplansmb : All done!
> 2023-03-24 10:53:58 : REQ   : crashplansmb : ################## End Installomator, exit code 0

**Comment by orrison-CrashPlan** [comment]
I think we need two labels.

One for CrashPlan
```
crashplan)
    name="CrashPlan"
    type="pkgInDmg"
    pkgName="Install CrashPlan.pkg"
    downloadURL="https://download.crashplan.com/installs/agent/latest-mac.dmg"
    expectedTeamID="UGHXR79U6M"
    blockingProcesses=( NONE )
    ;;
```
One for CrashPlan SMB
```
crashplansmb)
    name="CrashPlan"
    type="pkgInDmg"
    pkgName="Install CrashPlan.pkg"
    downloadURL="https://download.crashplan.com/installs/agent/latest-smb-mac.dmg"
    expectedTeamID="UGHXR79U6M"
    blockingProcesses=( NONE )
    ;;
```

**Comment by jnichols35** [comment]
@orrison-CrashPlan I made a separate PR for crashplan: https://github.com/Installomator/Installomator/pull/966

**Comment by Mac-Nerd** [comment]
add: 

```appNewVersion=$( curl https://download.crashplan.com/installs/agent/latest-smb-mac.dmg  -s -L -I -o /dev/null -w '%{url_effective}' | cut -d "/" -f7 )```

**Comment by scriptingosx** [comment]
Thank you!

**Pull request merged**
