### PR TITLE
Update tunnelblick.sh

### PR DESCRIPTION
**Pull request by macmangr**
Added appNewVersion check

./assemble.sh -l /Desktop/Mosyle/Resources/InstallomatorLabels tunnelblick NOTIFY=silent DEBUG=0
Password:
2022-07-09 13:38:40 : WARN  : tunnelblick : setting variable from argument NOTIFY=silent
2022-07-09 13:38:40 : WARN  : tunnelblick : setting variable from argument DEBUG=0
2022-07-09 13:38:40 : REQ   : tunnelblick : ################## Start Installomator v. 10.0beta, date 2022-07-09
2022-07-09 13:38:40 : INFO  : tunnelblick : ################## Version: 10.0beta
2022-07-09 13:38:40 : INFO  : tunnelblick : ################## Date: 2022-07-09
2022-07-09 13:38:40 : INFO  : tunnelblick : ################## tunnelblick
2022-07-09 13:38:43 : INFO  : tunnelblick : BLOCKING_PROCESS_ACTION=tell_user
2022-07-09 13:38:43 : INFO  : tunnelblick : NOTIFY=silent
2022-07-09 13:38:43 : INFO  : tunnelblick : LOGGING=INFO
2022-07-09 13:38:43 : INFO  : tunnelblick : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2022-07-09 13:38:43 : INFO  : tunnelblick : Label type: dmg
2022-07-09 13:38:43 : INFO  : tunnelblick : archiveName: Tunnelblick.dmg
2022-07-09 13:38:43 : INFO  : tunnelblick : no blocking processes defined, using Tunnelblick as default
2022-07-09 13:38:43 : INFO  : tunnelblick : App(s) found: /Applications/Tunnelblick.app
2022-07-09 13:38:43 : INFO  : tunnelblick : found app at /Applications/Tunnelblick.app, version 3.8.8beta04 (build 5800), on versionKey CFBundleShortVersionString
2022-07-09 13:38:43 : INFO  : tunnelblick : appversion: 3.8.8beta04 (build 5800)
2022-07-09 13:38:43 : INFO  : tunnelblick : Latest version of Tunnelblick is 3.8.8beta04 (build 5800)
2022-07-09 13:38:43 : INFO  : tunnelblick : There is no newer version available.
2022-07-09 13:38:43 : INFO  : tunnelblick : App not closed, so no reopen.
2022-07-09 13:38:43 : REQ   : tunnelblick : No newer version.
2022-07-09 13:38:43 : REQ   : tunnelblick : ################## End Installomator, exit code 0

### CODE REVIEW

**Comment by Theile** [comment]
This is locating beta-software. I think we should stick to full ordinary releases.

**Comment by acodega** [comment]
But that's no different from what Installomator will install either, since Tunnelblick posts the beta release as "latest". Tunnelblick recommends beta releases for the latest bug and security fixes and OS support. It's not unusual to deploy the latest beta version. [We had discussed this earlier.](https://github.com/Installomator/Installomator/issues/647)

**Comment by scriptingosx** [comment]
Thank you!

**Comment by scriptingosx** [comment]
Thank you!

**Comment by scriptingosx** [comment]
generally we wouldn't want to download a beta, but tunnelblick is weird this way...

**Pull request merged**
