### PR TITLE
`appNewVersion` on defaultfolderx

### PR DESCRIPTION
**Pull request by Theile**
Default Folder X with version control.

### CODE REVIEW

**Comment by acodega** [comment]
This PR has more than just the defaultfolderx commit, want to edit the PR or cancel it?

**Comment by Theile** [comment]
This PR is the changes in labels between my fork’s version 0.6.0 and this one. All of these labels should be updated. And one removed if I’m remembering it correctly (it was a duplicate).

**Comment by scriptingosx** [comment]
Not sure how to merge this into the fragments branch. Maybe you can sort this out after we merge fragments?

**Comment by Theile** [comment]
OK, I can merge them manually…

**Pull request closed without merging**
