### PR TITLE
New Label: Projectplace

### PR DESCRIPTION
**Pull request by kryptonit1**
2022-09-13 08:38:09 : REQ   : projectplace : ################## Start Installomator v. 10.0beta3, date 2022-09-13
2022-09-13 08:38:09 : INFO  : projectplace : ################## Version: 10.0beta3
2022-09-13 08:38:09 : INFO  : projectplace : ################## Date: 2022-09-13
2022-09-13 08:38:09 : INFO  : projectplace : ################## projectplace
2022-09-13 08:38:09 : INFO  : projectplace : SwiftDialog is not installed, clear cmd file var
2022-09-13 08:38:09 : INFO  : projectplace : BLOCKING_PROCESS_ACTION=tell_user
2022-09-13 08:38:09 : INFO  : projectplace : NOTIFY=success
2022-09-13 08:38:09 : INFO  : projectplace : LOGGING=INFO
2022-09-13 08:38:09 : INFO  : projectplace : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2022-09-13 08:38:09 : INFO  : projectplace : Label type: dmg
2022-09-13 08:38:09 : INFO  : projectplace : archiveName: Projectplace.dmg
2022-09-13 08:38:09 : INFO  : projectplace : no blocking processes defined, using Projectplace as default
2022-09-13 08:38:10 : INFO  : projectplace : name: Projectplace, appName: Projectplace.app
2022-09-13 08:38:10 : WARN  : projectplace : No previous app found
2022-09-13 08:38:10 : WARN  : projectplace : could not find Projectplace.app
2022-09-13 08:38:10 : INFO  : projectplace : appversion:
2022-09-13 08:38:10 : INFO  : projectplace : Latest version not specified.
2022-09-13 08:38:10 : REQ   : projectplace : Downloading https://service.projectplace.com/client_apps/desktop/Projectplace-for-mac.dmg to Projectplace.dmg
2022-09-13 08:38:11 : REQ   : projectplace : no more blocking processes, continue with update
2022-09-13 08:38:11 : REQ   : projectplace : Installing Projectplace
2022-09-13 08:38:11 : INFO  : projectplace : Mounting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.DSQ0lE6Y/Projectplace.dmg
2022-09-13 08:38:14 : INFO  : projectplace : Mounted: /Volumes/Projectplace
2022-09-13 08:38:14 : INFO  : projectplace : Verifying: /Volumes/Projectplace/Projectplace.app
2022-09-13 08:38:15 : INFO  : projectplace : Team ID matching: 8333HW99E8 (expected: 8333HW99E8 )
2022-09-13 08:38:15 : INFO  : projectplace : Installing Projectplace version 1.3.5 on versionKey CFBundleShortVersionString.
2022-09-13 08:38:15 : INFO  : projectplace : Copy /Volumes/Projectplace/Projectplace.app to /Applications
2022-09-13 08:38:15 : WARN  : projectplace : Changing owner to kryptonit
2022-09-13 08:38:15 : INFO  : projectplace : Finishing...
2022-09-13 08:38:18 : INFO  : projectplace : App(s) found: /Applications/Projectplace.app
2022-09-13 08:38:18 : INFO  : projectplace : found app at /Applications/Projectplace.app, version 1.3.5, on versionKey CFBundleShortVersionString
2022-09-13 08:38:18 : REQ   : projectplace : Installed Projectplace, version 1.3.5
2022-09-13 08:38:18 : INFO  : projectplace : notifying
2022-09-13 08:38:19 : INFO  : projectplace : App not closed, so no reopen.
2022-09-13 08:38:19 : REQ   : projectplace : All done!
2022-09-13 08:38:19 : REQ   : projectplace : ################## End Installomator, exit code 0

### CODE REVIEW

**Comment by Theile** [comment]
What about `appNewVersion`? That is very important. Let us know if you need help with it.

**Comment by kryptonit1** [comment]
> What about `appNewVersion`? That is very important. Let us know if you need help with it.

I've so far not found a way to fetch the latest version of this application from somewhere. It does not seem to be listed anywhere on the developer's web site or in the download URL:

https://www.planview.com/products-solutions/products/projectplace/projectplace-download/

And there does not seem to be a sparkle feed available.

**Comment by scriptingosx** [comment]
Thank you!

**Comment by scriptingosx** [comment]
Thank you!

**Pull request merged**
