### PR TITLE
Update clickshare.sh

### PR DESCRIPTION
**Pull request by TacoDienstag**
Updated variable downloadURL and appNewVersion to work with the latest releases of Clickshare

### CODE REVIEW

**Comment by TacoDienstag** [comment]
2023-11-02 12:55:30 : REQ   : clickshare : ################## Start Installomator v. 10.6beta, date 2023-11-02
2023-11-02 12:55:30 : INFO  : clickshare : ################## Version: 10.6beta
2023-11-02 12:55:30 : INFO  : clickshare : ################## Date: 2023-11-02
2023-11-02 12:55:30 : INFO  : clickshare : ################## clickshare
2023-11-02 12:55:30 : DEBUG : clickshare : DEBUG mode 1 enabled.
2023-11-02 12:55:30 : DEBUG : clickshare : name=ClickShare
2023-11-02 12:55:30 : DEBUG : clickshare : appName=
2023-11-02 12:55:30 : DEBUG : clickshare : type=appInDmgInZip
2023-11-02 12:55:30 : DEBUG : clickshare : archiveName=
2023-11-02 12:55:30 : DEBUG : clickshare : downloadURL=https://securefiles.barco.com/tde/Active/SoftwareFiles/ApplicationSoftware/R3306192_51_ApplicationSw.zip?t=Y8i7nBnJBssY8tWwZZDlQ0QZ0WtMxFLy7hJ%2bu%2f4PlPY%3d&e=1698926430561&sv=2021-08-06&spr=https&st=2023-11-02T11%3A55%3A30Z&se=2023-11-02T12%3A00%3A30Z&sr=f&sp=r&sig=FNFm9nvEoZeZ4QHk9cT5nI0jpB2z3yo%2BZrS02So%2Fq5k%3D
2023-11-02 12:55:30 : DEBUG : clickshare : curlOptions=
2023-11-02 12:55:30 : DEBUG : clickshare : appNewVersion=4.33.0-b8
2023-11-02 12:55:30 : DEBUG : clickshare : appCustomVersion function: Not defined
2023-11-02 12:55:30 : DEBUG : clickshare : versionKey=CFBundleShortVersionString
2023-11-02 12:55:30 : DEBUG : clickshare : packageID=
2023-11-02 12:55:30 : DEBUG : clickshare : pkgName=
2023-11-02 12:55:30 : DEBUG : clickshare : choiceChangesXML=
2023-11-02 12:55:30 : DEBUG : clickshare : expectedTeamID=P6CDJZR997
2023-11-02 12:55:30 : DEBUG : clickshare : blockingProcesses=
2023-11-02 12:55:30 : DEBUG : clickshare : installerTool=
2023-11-02 12:55:30 : DEBUG : clickshare : CLIInstaller=
2023-11-02 12:55:30 : DEBUG : clickshare : CLIArguments=
2023-11-02 12:55:30 : DEBUG : clickshare : updateTool=
2023-11-02 12:55:30 : DEBUG : clickshare : updateToolArguments=
2023-11-02 12:55:30 : DEBUG : clickshare : updateToolRunAsCurrentUser=
2023-11-02 12:55:30 : INFO  : clickshare : BLOCKING_PROCESS_ACTION=tell_user
2023-11-02 12:55:30 : INFO  : clickshare : NOTIFY=success
2023-11-02 12:55:30 : INFO  : clickshare : LOGGING=DEBUG
2023-11-02 12:55:30 : INFO  : clickshare : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2023-11-02 12:55:30 : INFO  : clickshare : Label type: appInDmgInZip
2023-11-02 12:55:30 : INFO  : clickshare : archiveName: ClickShare.zip
2023-11-02 12:55:30 : INFO  : clickshare : no blocking processes defined, using ClickShare as default
2023-11-02 12:55:30 : DEBUG : clickshare : Changing directory to /Users/b.kollmer/Development/Installomator/Installomator/build
2023-11-02 12:55:30 : INFO  : clickshare : name: ClickShare, appName: ClickShare.app
2023-11-02 12:55:30.938 mdfind[46901:16539129] [UserQueryParser] Loading keywords and predicates for locale "de_DE"
2023-11-02 12:55:30.938 mdfind[46901:16539129] [UserQueryParser] Loading keywords and predicates for locale "de"
2023-11-02 12:55:30.992 mdfind[46901:16539129] Couldn't determine the mapping between prefab keywords and predicates.
2023-11-02 12:55:31 : WARN  : clickshare : No previous app found
2023-11-02 12:55:31 : WARN  : clickshare : could not find ClickShare.app
2023-11-02 12:55:31 : INFO  : clickshare : appversion: 
2023-11-02 12:55:31 : INFO  : clickshare : Latest version of ClickShare is 4.33.0-b8
2023-11-02 12:55:31 : INFO  : clickshare : ClickShare.zip exists and DEBUG mode 1 enabled, skipping download
2023-11-02 12:55:31 : DEBUG : clickshare : DEBUG mode 1, not checking for blocking processes
2023-11-02 12:55:31 : REQ   : clickshare : Installing ClickShare
2023-11-02 12:55:31 : INFO  : clickshare : Unzipping ClickShare.zip
2023-11-02 12:55:31 : INFO  : clickshare : found dmg: /Users/b.kollmer/Development/Installomator/Installomator/build/ClickShare_Setup.dmg
2023-11-02 12:55:31 : INFO  : clickshare : Mounting /Users/b.kollmer/Development/Installomator/Installomator/build/ClickShare_Setup.dmg
2023-11-02 12:55:35 : DEBUG : clickshare : Debugging enabled, dmgmount output was:
Prüfsumme für Protective Master Boot Record (MBR : 0) berechnen …
Protective Master Boot Record (MBR :: Die überprüfte CRC32-Prüfsumme ist $A74C126A
Prüfsumme für GPT Header (Primary GPT Header : 1) berechnen …
GPT Header (Primary GPT Header : 1): Die überprüfte CRC32-Prüfsumme ist $E95C04C1
Prüfsumme für GPT Partition Data (Primary GPT Table : 2) berechnen …
GPT Partition Data (Primary GPT Tabl: Die überprüfte CRC32-Prüfsumme ist $CE2E6717
Prüfsumme für  (Apple_Free : 3) berechnen …
(Apple_Free : 3): Die überprüfte CRC32-Prüfsumme ist $00000000
Prüfsumme für disk image (Apple_HFS : 4) berechnen …
disk image (Apple_HFS : 4): Die überprüfte CRC32-Prüfsumme ist $237ED232
Prüfsumme für  (Apple_Free : 5) berechnen …
(Apple_Free : 5): Die überprüfte CRC32-Prüfsumme ist $00000000
Prüfsumme für GPT Partition Data (Backup GPT Table : 6) berechnen …
GPT Partition Data (Backup GPT Table: Die überprüfte CRC32-Prüfsumme ist $CE2E6717
Prüfsumme für GPT Header (Backup GPT Header : 7) berechnen …
GPT Header (Backup GPT Header : 7): Die überprüfte CRC32-Prüfsumme ist $A1E15B75
Die überprüfte CRC32-Prüfsumme ist $BEB2A5C2
/dev/disk4              GUID_partition_scheme
/dev/disk4s1            Apple_HFS                       /Volumes/ClickShare Client

2023-11-02 12:55:35 : INFO  : clickshare : Mounted: /Volumes/ClickShare Client
2023-11-02 12:55:35 : INFO  : clickshare : Verifying: /Volumes/ClickShare Client/ClickShare.app
2023-11-02 12:55:35 : DEBUG : clickshare : App size: 125M       /Volumes/ClickShare Client/ClickShare.app
2023-11-02 12:55:35 : DEBUG : clickshare : Debugging enabled, App Verification output was:
/Volumes/ClickShare Client/ClickShare.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: Barco NV (P6CDJZR997)

2023-11-02 12:55:35 : INFO  : clickshare : Team ID matching: P6CDJZR997 (expected: P6CDJZR997 )
2023-11-02 12:55:35 : INFO  : clickshare : Installing ClickShare version 4.33.0-b8 on versionKey CFBundleShortVersionString.
2023-11-02 12:55:35 : INFO  : clickshare : App has LSMinimumSystemVersion: 10.13
2023-11-02 12:55:35 : DEBUG : clickshare : DEBUG mode 1 enabled, skipping remove, copy and chown steps
2023-11-02 12:55:35 : INFO  : clickshare : Finishing...
2023-11-02 12:55:38 : INFO  : clickshare : name: ClickShare, appName: ClickShare.app
2023-11-02 12:55:38.863 mdfind[47034:16539757] [UserQueryParser] Loading keywords and predicates for locale "de_DE"
2023-11-02 12:55:38.863 mdfind[47034:16539757] [UserQueryParser] Loading keywords and predicates for locale "de"
2023-11-02 12:55:38.917 mdfind[47034:16539757] Couldn't determine the mapping between prefab keywords and predicates.
2023-11-02 12:55:39 : WARN  : clickshare : No previous app found
2023-11-02 12:55:39 : WARN  : clickshare : could not find ClickShare.app
2023-11-02 12:55:39 : REQ   : clickshare : Installed ClickShare, version 4.33.0-b8
2023-11-02 12:55:39 : INFO  : clickshare : notifying
2023-11-02 12:55:39 : DEBUG : clickshare : Unmounting /Volumes/ClickShare Client
2023-11-02 12:55:39 : DEBUG : clickshare : Debugging enabled, Unmounting output was:
"disk4" ejected.
2023-11-02 12:55:39 : DEBUG : clickshare : DEBUG mode 1, not reopening anything
2023-11-02 12:55:39 : REQ   : clickshare : All done!
2023-11-02 12:55:39 : REQ   : clickshare : ################## End Installomator, exit code 0

**Comment by kevinVodi** [comment]
Install is still failing. Latest URL I see for the MAC download:

https://securefiles.barco.com/tde/Active/SoftwareFiles/ApplicationSoftware/R3306192_53_ApplicationSw.zip?t=Y3OFszUhy9jI11sr%2b7tXolzGmkDieAhhCZnhT7GRQNQ%3d&e=1707341175175&sv=2021-08-06&spr=https&st=2024-02-07T21%3A21%3A15Z&se=2024-02-07T21%3A26%3A15Z&sr=f&sp=r&sig=0JloEC2yfOMQFYF%2BrC4ReCN%2BmGG9GYsJOJW6FMEnv2M%3D

**Comment by kevinVodi** [comment]
> @kevinVodi can't relate to that. I checked the Label and everything's working fine. See the output below:
> 
> 2024-02-08 11:04:08 : REQ : clickshare : ################## Start Installomator v. 10.6beta, date 2024-02-08 2024-02-08 11:04:08 : INFO : clickshare : ################## Version: 10.6beta 2024-02-08 11:04:08 : INFO : clickshare : ################## Date: 2024-02-08 2024-02-08 11:04:08 : INFO : clickshare : ################## clickshare 2024-02-08 11:04:08 : DEBUG : clickshare : DEBUG mode 1 enabled. 2024-02-08 11:04:09 : DEBUG : clickshare : name=ClickShare 2024-02-08 11:04:09 : DEBUG : clickshare : appName= 2024-02-08 11:04:09 : DEBUG : clickshare : type=appInDmgInZip 2024-02-08 11:04:09 : DEBUG : clickshare : archiveName= 2024-02-08 11:04:09 : DEBUG : clickshare : downloadURL=https://securefiles.barco.com/tde/Active/SoftwareFiles/ApplicationSoftware/R3306192_53_ApplicationSw.zip?t=XmxjtNj6Q0EZcYZgI4rm%2b8Icwyg0YAXLpgBPEIK21sY%3d&e=1707386949075&sv=2021-08-06&spr=https&st=2024-02-08T10%3A04%3A09Z&se=2024-02-08T10%3A09%3A09Z&sr=f&sp=r&sig=eFVwNdVIsZqg3z4PB%2BRg3AwskbBe%2BXMwPZniIW0WtJM%3D 2024-02-08 11:04:09 : DEBUG : clickshare : curlOptions= 2024-02-08 11:04:09 : DEBUG : clickshare : appNewVersion=4.35.0-b17 2024-02-08 11:04:09 : DEBUG : clickshare : appCustomVersion function: Not defined 2024-02-08 11:04:09 : DEBUG : clickshare : versionKey=CFBundleShortVersionString 2024-02-08 11:04:09 : DEBUG : clickshare : packageID= 2024-02-08 11:04:09 : DEBUG : clickshare : pkgName= 2024-02-08 11:04:09 : DEBUG : clickshare : choiceChangesXML= 2024-02-08 11:04:09 : DEBUG : clickshare : expectedTeamID=P6CDJZR997 2024-02-08 11:04:09 : DEBUG : clickshare : blockingProcesses= 2024-02-08 11:04:09 : DEBUG : clickshare : installerTool= 2024-02-08 11:04:09 : DEBUG : clickshare : CLIInstaller= 2024-02-08 11:04:09 : DEBUG : clickshare : CLIArguments= 2024-02-08 11:04:09 : DEBUG : clickshare : updateTool= 2024-02-08 11:04:09 : DEBUG : clickshare : updateToolArguments= 2024-02-08 11:04:09 : DEBUG : clickshare : updateToolRunAsCurrentUser= 2024-02-08 11:04:09 : INFO : clickshare : BLOCKING_PROCESS_ACTION=tell_user 2024-02-08 11:04:09 : INFO : clickshare : NOTIFY=success 2024-02-08 11:04:09 : INFO : clickshare : LOGGING=DEBUG 2024-02-08 11:04:09 : INFO : clickshare : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns 2024-02-08 11:04:09 : INFO : clickshare : Label type: appInDmgInZip 2024-02-08 11:04:09 : INFO : clickshare : archiveName: ClickShare.zip 2024-02-08 11:04:09 : INFO : clickshare : no blocking processes defined, using ClickShare as default 2024-02-08 11:04:09 : DEBUG : clickshare : Changing directory to /Users/b.kollmer/Development/Installomator/Installomator/build 2024-02-08 11:04:09 : INFO : clickshare : name: ClickShare, appName: ClickShare.app 2024-02-08 11:04:09.197 mdfind[28495:3997472] [UserQueryParser] Loading keywords and predicates for locale "de_DE" 2024-02-08 11:04:09.197 mdfind[28495:3997472] [UserQueryParser] Loading keywords and predicates for locale "de" 2024-02-08 11:04:09.264 mdfind[28495:3997472] Couldn't determine the mapping between prefab keywords and predicates. 2024-02-08 11:04:09 : WARN : clickshare : No previous app found 2024-02-08 11:04:09 : WARN : clickshare : could not find ClickShare.app 2024-02-08 11:04:09 : INFO : clickshare : appversion: 2024-02-08 11:04:09 : INFO : clickshare : Latest version of ClickShare is 4.35.0-b17 2024-02-08 11:04:09 : REQ : clickshare : Downloading https://securefiles.barco.com/tde/Active/SoftwareFiles/ApplicationSoftware/R3306192_53_ApplicationSw.zip?t=XmxjtNj6Q0EZcYZgI4rm%2b8Icwyg0YAXLpgBPEIK21sY%3d&e=1707386949075&sv=2021-08-06&spr=https&st=2024-02-08T10%3A04%3A09Z&se=2024-02-08T10%3A09%3A09Z&sr=f&sp=r&sig=eFVwNdVIsZqg3z4PB%2BRg3AwskbBe%2BXMwPZniIW0WtJM%3D to ClickShare.zip 2024-02-08 11:04:09 : DEBUG : clickshare : No Dialog connection, just download 2024-02-08 11:04:14 : DEBUG : clickshare : File list: -rw-r--r-- 1 root staff 121M 8 Feb 11:04 ClickShare.zip 2024-02-08 11:04:14 : DEBUG : clickshare : File type: ClickShare.zip: Zip archive data, at least v2.0 to extract, compression method=deflate 2024-02-08 11:04:14 : DEBUG : clickshare : curl output was:
> 
> * Trying 104.18.6.213:443...
> * Connected to securefiles.barco.com (104.18.6.213) port 443
> * ALPN: curl offers h2,http/1.1
> * (304) (OUT), TLS handshake, Client hello (1):
>   } [326 bytes data]
> * CAfile: /etc/ssl/cert.pem
> * CApath: none
> * (304) (IN), TLS handshake, Server hello (2):
>   { [122 bytes data]
> * (304) (IN), TLS handshake, Unknown (8):
>   { [19 bytes data]
> * (304) (IN), TLS handshake, Certificate (11):
>   { [2304 bytes data]
> * (304) (IN), TLS handshake, CERT verify (15):
>   { [79 bytes data]
> * (304) (IN), TLS handshake, Finished (20):
>   { [36 bytes data]
> * (304) (OUT), TLS handshake, Finished (20):
>   } [36 bytes data]
> * SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
> * ALPN: server accepted h2
> * Server certificate:
> * subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=securefiles.barco.com
> * start date: Sep 14 00:00:00 2023 GMT
> * expire date: Sep 12 23:59:59 2024 GMT
> * subjectAltName: host "securefiles.barco.com" matched cert's "securefiles.barco.com"
> * issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
> * SSL certificate verify ok.
> * using HTTP/2
> * [HTTP/2] [1] OPENED stream for https://securefiles.barco.com/tde/Active/SoftwareFiles/ApplicationSoftware/R3306192_53_ApplicationSw.zip?t=XmxjtNj6Q0EZcYZgI4rm%2b8Icwyg0YAXLpgBPEIK21sY%3d&e=1707386949075&sv=2021-08-06&spr=https&st=2024-02-08T10%3A04%3A09Z&se=2024-02-08T10%3A09%3A09Z&sr=f&sp=r&sig=eFVwNdVIsZqg3z4PB%2BRg3AwskbBe%2BXMwPZniIW0WtJM%3D
> * [HTTP/2] [1] [:method: GET]
> * [HTTP/2] [1] [:scheme: https]
> * [HTTP/2] [1] [:authority: securefiles.barco.com]
> * [HTTP/2] [1] [:path: /tde/Active/SoftwareFiles/ApplicationSoftware/R3306192_53_ApplicationSw.zip?t=XmxjtNj6Q0EZcYZgI4rm%2b8Icwyg0YAXLpgBPEIK21sY%3d&e=1707386949075&sv=2021-08-06&spr=https&st=2024-02-08T10%3A04%3A09Z&se=2024-02-08T10%3A09%3A09Z&sr=f&sp=r&sig=eFVwNdVIsZqg3z4PB%2BRg3AwskbBe%2BXMwPZniIW0WtJM%3D]
> * [HTTP/2] [1] [user-agent: curl/8.4.0]
> * [HTTP/2] [1] [accept: _/_]
> 
> > GET /tde/Active/SoftwareFiles/ApplicationSoftware/R3306192_53_ApplicationSw.zip?t=XmxjtNj6Q0EZcYZgI4rm%2b8Icwyg0YAXLpgBPEIK21sY%3d&e=1707386949075&sv=2021-08-06&spr=https&st=2024-02-08T10%3A04%3A09Z&se=2024-02-08T10%3A09%3A09Z&sr=f&sp=r&sig=eFVwNdVIsZqg3z4PB%2BRg3AwskbBe%2BXMwPZniIW0WtJM%3D HTTP/2
> > Host: securefiles.barco.com
> > User-Agent: curl/8.4.0
> > Accept: _/_
> 
> < HTTP/2 200 < date: Thu, 08 Feb 2024 10:04:09 GMT < content-type: application/octet-stream < content-length: 126771479 < cf-ray: 85230c009a6c0497-FRA < cf-cache-status: HIT < accept-ranges: bytes < age: 532384 < cache-control: public, max-age=14400 < etag: "0x8DC183EAE5EDCFE" < expires: Thu, 08 Feb 2024 14:04:09 GMT < last-modified: Thu, 18 Jan 2024 16:01:07 GMT < debug: {"tokenExp":"2024-02-08T10:09:09.075Z","fullPath":"/tde/Active/SoftwareFiles/ApplicationSoftware/R3306192_53_ApplicationSw.zip","filePath":"/Active/SoftwareFiles/ApplicationSoftware/R3306192_53_ApplicationSw.zip","fileName":"R3306192_53_ApplicationSw.zip","storagePath":"/barcoprdfs/Data/secure/downloads/tde/Active/SoftwareFiles/ApplicationSoftware/R3306192_53_ApplicationSw.zip","cf":{"cacheTtlByStatus":{"100-199":0,"200-299":1209600,"300-399":30,"400-499":10,"500-599":0},"cacheEverything":true,"cacheKey":"/Active/SoftwareFiles/ApplicationSoftware/R3306192_53_ApplicationSw.zip"}} < x-ms-file-attributes: Archive < x-ms-file-change-time: 2024-01-18T16:01:07.2259326Z < x-ms-file-creation-time: 2024-01-18T16:00:55.7173145Z < x-ms-file-id: 11529318261648785408 < x-ms-file-last-write-time: 2024-01-18T15:14:40.0837100Z < x-ms-file-parent-id: 10979272315203747840 < x-ms-file-permission-key: 6727408348044536465*17725154925850968607 < x-ms-lease-state: available < x-ms-lease-status: unlocked < x-ms-request-id: e5ae4120-e01a-0039-179e-55f5ca000000 < x-ms-server-encrypted: true < x-ms-type: File < x-ms-version: 2021-08-06 < server: cloudflare < { [42333 bytes data]
> 
> * Connection #0 to host securefiles.barco.com left intact
> 
> 2024-02-08 11:04:14 : DEBUG : clickshare : DEBUG mode 1, not checking for blocking processes 2024-02-08 11:04:14 : REQ : clickshare : Installing ClickShare 2024-02-08 11:04:14 : INFO : clickshare : Unzipping ClickShare.zip 2024-02-08 11:04:15 : INFO : clickshare : found dmg: /Users/b.kollmer/Development/Installomator/Installomator/build/ClickShare_Setup.dmg 2024-02-08 11:04:15 : INFO : clickshare : Mounting /Users/b.kollmer/Development/Installomator/Installomator/build/ClickShare_Setup.dmg 2024-02-08 11:04:18 : DEBUG : clickshare : Debugging enabled, dmgmount output was: Prüfsumme für Protective Master Boot Record (MBR : 0) berechnen … Protective Master Boot Record (MBR :: Die überprüfte CRC32-Prüfsumme ist $7EC1CB1A Prüfsumme für GPT Header (Primary GPT Header : 1) berechnen … GPT Header (Primary GPT Header : 1): Die überprüfte CRC32-Prüfsumme ist $D8C916D4 Prüfsumme für GPT Partition Data (Primary GPT Table : 2) berechnen … GPT Partition Data (Primary GPT Tabl: Die überprüfte CRC32-Prüfsumme ist $85D49EEA Prüfsumme für (Apple_Free : 3) berechnen … (Apple_Free : 3): Die überprüfte CRC32-Prüfsumme ist $00000000 Prüfsumme für disk image (Apple_HFS : 4) berechnen … disk image (Apple_HFS : 4): Die überprüfte CRC32-Prüfsumme ist $9007E140 Prüfsumme für (Apple_Free : 5) berechnen … (Apple_Free : 5): Die überprüfte CRC32-Prüfsumme ist $00000000 Prüfsumme für GPT Partition Data (Backup GPT Table : 6) berechnen … GPT Partition Data (Backup GPT Table: Die überprüfte CRC32-Prüfsumme ist $85D49EEA Prüfsumme für GPT Header (Backup GPT Header : 7) berechnen … GPT Header (Backup GPT Header : 7): Die überprüfte CRC32-Prüfsumme ist $AB514996 Die überprüfte CRC32-Prüfsumme ist $83D0DBD7 /dev/disk4 GUID_partition_scheme /dev/disk4s1 Apple_HFS /Volumes/ClickShare Client
> 
> 2024-02-08 11:04:18 : INFO : clickshare : Mounted: /Volumes/ClickShare Client 2024-02-08 11:04:18 : INFO : clickshare : Verifying: /Volumes/ClickShare Client/ClickShare.app 2024-02-08 11:04:18 : DEBUG : clickshare : App size: 126M /Volumes/ClickShare Client/ClickShare.app 2024-02-08 11:04:18 : DEBUG : clickshare : Debugging enabled, App Verification output was: /Volumes/ClickShare Client/ClickShare.app: accepted source=Notarized Developer ID origin=Developer ID Application: Barco NV (P6CDJZR997)
> 
> 2024-02-08 11:04:18 : INFO : clickshare : Team ID matching: P6CDJZR997 (expected: P6CDJZR997 ) 2024-02-08 11:04:18 : INFO : clickshare : Installing ClickShare version 4.35.0-b17 on versionKey CFBundleShortVersionString. 2024-02-08 11:04:18 : INFO : clickshare : App has LSMinimumSystemVersion: 10.13 2024-02-08 11:04:18 : DEBUG : clickshare : DEBUG mode 1 enabled, skipping remove, copy and chown steps 2024-02-08 11:04:18 : INFO : clickshare : Finishing... 2024-02-08 11:04:21 : INFO : clickshare : name: ClickShare, appName: ClickShare.app 2024-02-08 11:04:21.644 mdfind[28654:3998295] [UserQueryParser] Loading keywords and predicates for locale "de_DE" 2024-02-08 11:04:21.644 mdfind[28654:3998295] [UserQueryParser] Loading keywords and predicates for locale "de" 2024-02-08 11:04:21.706 mdfind[28654:3998295] Couldn't determine the mapping between prefab keywords and predicates. 2024-02-08 11:04:21 : WARN : clickshare : No previous app found 2024-02-08 11:04:21 : WARN : clickshare : could not find ClickShare.app 2024-02-08 11:04:21 : REQ : clickshare : Installed ClickShare, version 4.35.0-b17 2024-02-08 11:04:21 : INFO : clickshare : notifying 2024-02-08 11:04:22 : DEBUG : clickshare : Unmounting /Volumes/ClickShare Client 2024-02-08 11:04:22 : DEBUG : clickshare : Debugging enabled, Unmounting output was: "disk4" ejected. 2024-02-08 11:04:22 : DEBUG : clickshare : DEBUG mode 1, not reopening anything 2024-02-08 11:04:22 : REQ : clickshare : All done! 2024-02-08 11:04:22 : REQ : clickshare : ################## End Installomator, exit code 0
> 
> Also checked the production script on one of our MDM Servers, everyhing's working:
> 
> Bildschirmfoto 2024-02-08 um 11 08 56
> Please share your whole debug log and maybe provide it in an issue as well. Maybe yout Firewall is blocking communication to some 3rd party services uses by barcoo.

I will test again but there is another report of a similar issue:
https://macadmins.slack.com/archives/C013HFTFQ13/p1708979360397689

**Comment by BigMacAdmin** [comment]
Thank you!

**Comment by kevinVodi** [comment]
Can confirm the ClickShare label is resolved. All is well in my testing - thanks!

**Pull request merged**
