### PR TITLE
Proxy Server Connectivity Optional Parameters

### PR DESCRIPTION
**Pull request by dionparsons**
Optional Setting for Proxy to be configured, JAMF Parameter Options 7 = Proxy Server and Parameter Options 8 = Proxy Port
If Parameters not set then blank values are put in for HTTP and HTTPS Proxy

### CODE REVIEW

**Comment by dionparsons** [comment]
@acodega Spelling Errors Fixed and Variables formatted with All Caps

**Comment by scriptingosx** [comment]
Installomator does not use fixed arguments like $7, $8 etc. doing that would break the other methods of supplying arguments.

Is there a way to pass the proxy config into `curl` with arguments? because then we should be able to leverage `curlOptions` without needing to change the code?

**Comment by dionparsons** [comment]
Using Curl options would mean having to modify all labels with a Curl command wouldn’t it?

I’ll look to modify the variable input method, see if that helps.

Ideally the proxy only gets used when Installomator.sh session is used and doesn’t affect the system, pretty sure it’s only a session proxy and thus applies to all outbound traffic from script not just Curl commands.

**Comment by scriptingosx** [comment]
> Using Curl options would mean having to modify all labels with a Curl command wouldn’t it?

Good point... There are ways. We could overload `curl` with a function of the same name (we do that with `xpath`) but that might break other uses.

**Comment by dionparsons** [comment]
Rewriting Code

**Pull request closed without merging**
