### PR TITLE
Detect spctl rejection

### PR DESCRIPTION
**Pull request by Theile**
Improved detection of spctl rejected, so we can suggest in the log to look at the gatekeeper setting (if it only allows App Store apps).

### CODE REVIEW

**Comment by Theile** [comment]
Output from Gatekeeper setting to App Store only:
```
➜  Installomator/utils/assemble.sh theunarchiver INSTALL=force DEBUG=0 LOGGING=ERROR
2022-04-07 20:10:22 : WARN  : theunarchiver : setting variable from argument INSTALL=force
2022-04-07 20:10:22 : WARN  : theunarchiver : setting variable from argument DEBUG=0
2022-04-07 20:10:22 : WARN  : theunarchiver : setting variable from argument LOGGING=ERROR
2022-04-07 20:10:22 : REQ   : theunarchiver : ################## Start Installomator v. 10dev, date 2022-04-07
2022-04-07 20:10:26 : REQ   : theunarchiver : Downloading https://dl.devmate.com/com.macpaw.site.theunarchiver/TheUnarchiver.dmg to The Unarchiver.dmg
2022-04-07 20:11:38 : REQ   : theunarchiver : no more blocking processes, continue with update
2022-04-07 20:11:38 : REQ   : theunarchiver : Installing The Unarchiver
2022-04-07 20:11:44 : ERROR : theunarchiver : Gatekeeper check rejected. Could be that gatekeeper settings only accept App Store apps.
2022-04-07 20:11:45 : ERROR : theunarchiver : ERROR: Error verifying /Volumes/The Unarchiver/The Unarchiver.app error:
/Volumes/The Unarchiver/The Unarchiver.app: rejected
source=Notarized Developer ID
origin=Developer ID Application: MacPaw Inc. (S8EX82NJP6)

2022-04-07 20:11:45 : REQ   : theunarchiver : ################## End Installomator, exit code 4 

➜  Installomator/utils/assemble.sh dockutil INSTALL=force DEBUG=0 LOGGING=ERROR
2022-04-07 20:12:16 : WARN  : dockutil : setting variable from argument INSTALL=force
2022-04-07 20:12:16 : WARN  : dockutil : setting variable from argument DEBUG=0
2022-04-07 20:12:16 : WARN  : dockutil : setting variable from argument LOGGING=ERROR
2022-04-07 20:12:16 : REQ   : dockutil : ################## Start Installomator v. 10dev, date 2022-04-07
2022-04-07 20:12:18 : REQ   : dockutil : Downloading https://github.com/kcrawford/dockutil/releases/download/3.0.2/dockutil-3.0.2.pkg to dockutil.pkg
2022-04-07 20:12:21 : REQ   : dockutil : Installing dockutil
2022-04-07 20:12:22 : ERROR : dockutil : Gatekeeper check rejected. Could be that gatekeeper settings only accept App Store apps.
2022-04-07 20:12:22 : ERROR : dockutil : ERROR: Error verifying dockutil.pkg error:
dockutil.pkg: rejected
source=Notarized Developer ID
origin=Developer ID Installer: Kyle Crawford (Z5J8CJBUWC)

2022-04-07 20:12:22 : REQ   : dockutil : ################## End Installomator, exit code 4 
```

**Comment by Theile** [comment]
OK, but I don't know how to check if only App Store apps are allowed or also identified developers.

`spctl --status` does not show any differences.

**Comment by scriptingosx** [comment]
Closing this for now until we find a solution

**Comment by PicoMitchell** [comment]
I was talking with @scriptingosx about this earlier and got curious and did a little poking and figured out how to determine if the macOS is currently allowing only Mac App Store apps or is also allowing Developer ID apps.

The info is stored in a SQLite3 database at `/private/var/db/SystemPolicy` (which is mentioned in the `FILES` section of `man spctl` but I also found it from watching files with `FSMonitor` while changing the setting) which contains rows for Code Signing Requirement (CSReq) conditions which are currently allowed to run, and I built this query to check if any of the Developer ID entries are NOT disabled:
```
sqlite3 '/private/var/db/SystemPolicy' 'SELECT DISTINCT disabled FROM authority WHERE requirement LIKE "%certificate leaf[field.1.2.840.113635.100.6.1.13] exists%" AND disabled = 0'
```
_(This command must be run as root to be able to read the `/private/var/db/SystemPolicy` file.)_

It outputs nothing when only Mac App Store apps are allowed, and outputs “0" when Developer ID apps are also allowed to run (because I’m outputting _distinct_ values from the `disabled` fields which contains CSReqs referencing the Dev ID certs).

So, a condition to check this could look like:
```
if [[ -z "$(sqlite3 '/private/var/db/SystemPolicy' 'SELECT DISTINCT disabled FROM authority WHERE requirement LIKE "%certificate leaf[field.1.2.840.113635.100.6.1.13] exists%" AND disabled = 0')" ]]; then
    echo 'Only Mac App Store apps are allowed to run!'
else
    echo 'Both Mac App Store apps and apps from identified developers (signed with Developer ID certificates) are allowed to run!'
fi
```
If you haven’t come across `certificate leaf[field.1.2.840.113635.100.6.1.13] exists` before, it’s just an explicit way to check for Dev ID certs. https://developer.apple.com/documentation/technotes/tn3127-inside-code-signing-requirements#Developer-ID-default-designated-requirement describes it as:

> The certificate leaf[field.1.2.840.113635.100.6.1.13] term requires that the certificate that issued the signing certificate include an extension with the OID 1.2.840.113635.100.6.1.13. This OID is present in the Developer ID Application signing certificates issued by Apple.

So, some condition like this could be used to just block `installomator` from running at all when only Mac App Store apps are allowed since nothing would be able to be installed anyways!

**Pull request closed without merging**
