### PR TITLE
Create snagit2024.sh

### PR DESCRIPTION
**Pull request by beatlemike**
Added TechSmith Snagit 2024

### CODE REVIEW

**Comment by beatlemike** [comment]
Sorry, ignore whatever I was doing with Label.txt. I lost my head completely for a minute

**Comment by beatlemike** [comment]
2023-10-04 13:58:09 : REQ   : snagit : ################## Start Installomator v. 10.5beta, date 2023-10-04
2023-10-04 13:58:09 : INFO  : snagit : ################## Version: 10.5beta
2023-10-04 13:58:09 : INFO  : snagit : ################## Date: 2023-10-04
2023-10-04 13:58:09 : INFO  : snagit : ################## snagit
2023-10-04 13:58:09 : DEBUG : snagit : DEBUG mode 1 enabled.
2023-10-04 13:58:10 : DEBUG : snagit : name=Snagit 2024
2023-10-04 13:58:10 : DEBUG : snagit : appName=
2023-10-04 13:58:10 : DEBUG : snagit : type=dmg
2023-10-04 13:58:10 : DEBUG : snagit : archiveName=
2023-10-04 13:58:10 : DEBUG : snagit : downloadURL=https://download.techsmith.com/snagitmac/releases/snagit.dmg
2023-10-04 13:58:10 : DEBUG : snagit : curlOptions=
2023-10-04 13:58:10 : DEBUG : snagit : appNewVersion=2024.0.0</p>
2023-10-04 13:58:10 : DEBUG : snagit : appCustomVersion function: Not defined
2023-10-04 13:58:10 : DEBUG : snagit : versionKey=CFBundleShortVersionString
2023-10-04 13:58:10 : DEBUG : snagit : packageID=
2023-10-04 13:58:10 : DEBUG : snagit : pkgName=
2023-10-04 13:58:10 : DEBUG : snagit : choiceChangesXML=
2023-10-04 13:58:10 : DEBUG : snagit : expectedTeamID=7TQL462TU8
2023-10-04 13:58:10 : DEBUG : snagit : blockingProcesses=
2023-10-04 13:58:10 : DEBUG : snagit : installerTool=
2023-10-04 13:58:10 : DEBUG : snagit : CLIInstaller=
2023-10-04 13:58:10 : DEBUG : snagit : CLIArguments=
2023-10-04 13:58:10 : DEBUG : snagit : updateTool=
2023-10-04 13:58:10 : DEBUG : snagit : updateToolArguments=
2023-10-04 13:58:10 : DEBUG : snagit : updateToolRunAsCurrentUser=
2023-10-04 13:58:10 : INFO  : snagit : BLOCKING_PROCESS_ACTION=tell_user
2023-10-04 13:58:10 : INFO  : snagit : NOTIFY=success
2023-10-04 13:58:10 : INFO  : snagit : LOGGING=DEBUG
2023-10-04 13:58:10 : INFO  : snagit : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2023-10-04 13:58:10 : INFO  : snagit : Label type: dmg
2023-10-04 13:58:10 : INFO  : snagit : archiveName: Snagit 2024.dmg
2023-10-04 13:58:10 : INFO  : snagit : no blocking processes defined, using Snagit 2024 as default
2023-10-04 13:58:10 : DEBUG : snagit : Changing directory to /Users/mfredette/Library/CloudStorage/OneDrive-CalPolyPomona/Documents/GitHub/Installomator/build
2023-10-04 13:58:10 : INFO  : snagit : App(s) found: /Applications/Snagit 2024.app
2023-10-04 13:58:10 : INFO  : snagit : found app at /Applications/Snagit 2024.app, version 2024.0.0, on versionKey CFBundleShortVersionString
2023-10-04 13:58:10 : INFO  : snagit : appversion: 2024.0.0
2023-10-04 13:58:10 : INFO  : snagit : Latest version of Snagit 2024 is 2024.0.0</p>
2023-10-04 13:58:10 : INFO  : snagit : Snagit 2024.dmg exists and DEBUG mode 1 enabled, skipping download
2023-10-04 13:58:10 : DEBUG : snagit : DEBUG mode 1, not checking for blocking processes
2023-10-04 13:58:10 : REQ   : snagit : Installing Snagit 2024
2023-10-04 13:58:10 : INFO  : snagit : Mounting /Users/mfredette/Library/CloudStorage/OneDrive-CalPolyPomona/Documents/GitHub/Installomator/build/Snagit 2024.dmg
2023-10-04 13:58:10 : DEBUG : snagit : Debugging enabled, dmgmount output was:
expected   CRC32 $9D527B49
/dev/disk5          	                               	/Volumes/Snagit 1

2023-10-04 13:58:10 : INFO  : snagit : Mounted: /Volumes/Snagit 1
2023-10-04 13:58:10 : INFO  : snagit : Verifying: /Volumes/Snagit 1/Snagit 2024.app
2023-10-04 13:58:10 : DEBUG : snagit : App size: 595M	/Volumes/Snagit 1/Snagit 2024.app
2023-10-04 13:58:14 : DEBUG : snagit : Debugging enabled, App Verification output was:
/Volumes/Snagit 1/Snagit 2024.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: TechSmith Corporation (7TQL462TU8)

2023-10-04 13:58:14 : INFO  : snagit : Team ID matching: 7TQL462TU8 (expected: 7TQL462TU8 )
2023-10-04 13:58:14 : INFO  : snagit : Downloaded version of Snagit 2024 is 2024.0.0 on versionKey CFBundleShortVersionString, same as installed.
2023-10-04 13:58:14 : DEBUG : snagit : Unmounting /Volumes/Snagit 1
2023-10-04 13:58:14 : DEBUG : snagit : Debugging enabled, Unmounting output was:
"disk5" ejected.
2023-10-04 13:58:14 : DEBUG : snagit : DEBUG mode 1, not reopening anything
2023-10-04 13:58:14 : REG   : snagit : No new version to install
2023-10-04 13:58:14 : REQ   : snagit : ################## End Installomator, exit code 0

**Comment by beatlemike** [comment]
2023-10-04 14:07:48 : REQ   : snagit2023 : ################## Start Installomator v. 10.5beta, date 2023-10-04
2023-10-04 14:07:48 : INFO  : snagit2023 : ################## Version: 10.5beta
2023-10-04 14:07:48 : INFO  : snagit2023 : ################## Date: 2023-10-04
2023-10-04 14:07:48 : INFO  : snagit2023 : ################## snagit2023
2023-10-04 14:07:48 : DEBUG : snagit2023 : DEBUG mode 1 enabled.
2023-10-04 14:07:49 : DEBUG : snagit2023 : name=Snagit 2023
2023-10-04 14:07:49 : DEBUG : snagit2023 : appName=
2023-10-04 14:07:49 : DEBUG : snagit2023 : type=dmg
2023-10-04 14:07:49 : DEBUG : snagit2023 : archiveName=
2023-10-04 14:07:49 : DEBUG : snagit2023 : downloadURL=https://download.techsmith.com/snagitmac/releases/2323/snagit.dmg
2023-10-04 14:07:49 : DEBUG : snagit2023 : curlOptions=
2023-10-04 14:07:49 : DEBUG : snagit2023 : appNewVersion=2023.2.3
2023-10-04 14:07:49 : DEBUG : snagit2023 : appCustomVersion function: Not defined
2023-10-04 14:07:49 : DEBUG : snagit2023 : versionKey=CFBundleShortVersionString
2023-10-04 14:07:49 : DEBUG : snagit2023 : packageID=
2023-10-04 14:07:49 : DEBUG : snagit2023 : pkgName=
2023-10-04 14:07:49 : DEBUG : snagit2023 : choiceChangesXML=
2023-10-04 14:07:49 : DEBUG : snagit2023 : expectedTeamID=7TQL462TU8
2023-10-04 14:07:49 : DEBUG : snagit2023 : blockingProcesses=
2023-10-04 14:07:49 : DEBUG : snagit2023 : installerTool=
2023-10-04 14:07:49 : DEBUG : snagit2023 : CLIInstaller=
2023-10-04 14:07:49 : DEBUG : snagit2023 : CLIArguments=
2023-10-04 14:07:49 : DEBUG : snagit2023 : updateTool=
2023-10-04 14:07:49 : DEBUG : snagit2023 : updateToolArguments=
2023-10-04 14:07:49 : DEBUG : snagit2023 : updateToolRunAsCurrentUser=
2023-10-04 14:07:49 : INFO  : snagit2023 : BLOCKING_PROCESS_ACTION=tell_user
2023-10-04 14:07:49 : INFO  : snagit2023 : NOTIFY=success
2023-10-04 14:07:49 : INFO  : snagit2023 : LOGGING=DEBUG
2023-10-04 14:07:49 : INFO  : snagit2023 : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2023-10-04 14:07:49 : INFO  : snagit2023 : Label type: dmg
2023-10-04 14:07:49 : INFO  : snagit2023 : archiveName: Snagit 2023.dmg
2023-10-04 14:07:49 : INFO  : snagit2023 : no blocking processes defined, using Snagit 2023 as default
2023-10-04 14:07:49 : DEBUG : snagit2023 : Changing directory to /Users/mfredette/Library/CloudStorage/OneDrive-CalPolyPomona/Documents/GitHub/Installomator/build
2023-10-04 14:07:49 : INFO  : snagit2023 : name: Snagit 2023, appName: Snagit 2023.app
2023-10-04 14:07:49.636 mdfind[24693:208366] [UserQueryParser] Loading keywords and predicates for locale "en_US"
2023-10-04 14:07:49.636 mdfind[24693:208366] [UserQueryParser] Loading keywords and predicates for locale "en"
2023-10-04 14:07:49.709 mdfind[24693:208366] Couldn't determine the mapping between prefab keywords and predicates.
2023-10-04 14:07:49 : WARN  : snagit2023 : No previous app found
2023-10-04 14:07:49 : WARN  : snagit2023 : could not find Snagit 2023.app
2023-10-04 14:07:49 : INFO  : snagit2023 : appversion: 
2023-10-04 14:07:49 : INFO  : snagit2023 : Latest version of Snagit 2023 is 2023.2.3
2023-10-04 14:07:49 : INFO  : snagit2023 : Snagit 2023.dmg exists and DEBUG mode 1 enabled, skipping download
2023-10-04 14:07:49 : DEBUG : snagit2023 : DEBUG mode 1, not checking for blocking processes
2023-10-04 14:07:49 : REQ   : snagit2023 : Installing Snagit 2023
2023-10-04 14:07:49 : INFO  : snagit2023 : Mounting /Users/mfredette/Library/CloudStorage/OneDrive-CalPolyPomona/Documents/GitHub/Installomator/build/Snagit 2023.dmg
2023-10-04 14:07:49 : DEBUG : snagit2023 : Debugging enabled, dmgmount output was:
expected   CRC32 $B0EBFA6B
/dev/disk5          	                               	/Volumes/Snagit 1

2023-10-04 14:07:49 : INFO  : snagit2023 : Mounted: /Volumes/Snagit 1
2023-10-04 14:07:49 : INFO  : snagit2023 : Verifying: /Volumes/Snagit 1/Snagit 2023.app
2023-10-04 14:07:50 : DEBUG : snagit2023 : App size: 493M	/Volumes/Snagit 1/Snagit 2023.app
2023-10-04 14:07:53 : DEBUG : snagit2023 : Debugging enabled, App Verification output was:
/Volumes/Snagit 1/Snagit 2023.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: TechSmith Corporation (7TQL462TU8)

2023-10-04 14:07:53 : INFO  : snagit2023 : Team ID matching: 7TQL462TU8 (expected: 7TQL462TU8 )
2023-10-04 14:07:53 : INFO  : snagit2023 : Installing Snagit 2023 version 2023.2.3 on versionKey CFBundleShortVersionString.
2023-10-04 14:07:53 : INFO  : snagit2023 : App has LSMinimumSystemVersion: 11.0
2023-10-04 14:07:53 : DEBUG : snagit2023 : DEBUG mode 1 enabled, skipping remove, copy and chown steps
2023-10-04 14:07:53 : INFO  : snagit2023 : Finishing...
2023-10-04 14:07:56 : INFO  : snagit2023 : name: Snagit 2023, appName: Snagit 2023.app
2023-10-04 14:07:56.449 mdfind[24776:208633] [UserQueryParser] Loading keywords and predicates for locale "en_US"
2023-10-04 14:07:56.450 mdfind[24776:208633] [UserQueryParser] Loading keywords and predicates for locale "en"
2023-10-04 14:07:56.510 mdfind[24776:208633] Couldn't determine the mapping between prefab keywords and predicates.
2023-10-04 14:07:56 : WARN  : snagit2023 : No previous app found
2023-10-04 14:07:56 : WARN  : snagit2023 : could not find Snagit 2023.app
2023-10-04 14:07:56 : REQ   : snagit2023 : Installed Snagit 2023, version 2023.2.3
2023-10-04 14:07:56 : INFO  : snagit2023 : notifying
2023-10-04 14:07:56 : DEBUG : snagit2023 : Unmounting /Volumes/Snagit 1
2023-10-04 14:07:56 : DEBUG : snagit2023 : Debugging enabled, Unmounting output was:
"disk5" ejected.
2023-10-04 14:07:56 : DEBUG : snagit2023 : DEBUG mode 1, not reopening anything
2023-10-04 14:07:56 : REQ   : snagit2023 : All done!
2023-10-04 14:07:56 : REQ   : snagit2023 : ################## End Installomator, exit code 0

**Comment by scriptingosx** [comment]
duplicate #1235

**Pull request merged**
