### PR TITLE
Jamf recon on success

### PR DESCRIPTION
**Pull request by dnikles**
It can be useful for jamf users to update inventory after software is successfully installed. This adds an argument JAMF_RECON_ON_SUCCESS that when set to yes will run a jamf recon. It defaults to no.

```
2022-05-26 15:24:33 : WARN  : zoom : setting variable from argument DEBUG=1
2022-05-26 15:24:34 : WARN  : zoom : setting variable from argument JAMF_RECON_ON_SUCCESS=yes
2022-05-26 15:24:34 : REQ   : zoom : ################## Start Installomator v. 10.0beta, date 2022-05-26
2022-05-26 15:24:34 : INFO  : zoom : ################## Version: 10.0beta
2022-05-26 15:24:34 : INFO  : zoom : ################## Date: 2022-05-26
2022-05-26 15:24:34 : INFO  : zoom : ################## zoom
2022-05-26 15:24:34 : DEBUG : zoom : DEBUG mode 1 enabled.
2022-05-26 15:24:34 : INFO  : zoom : BLOCKING_PROCESS_ACTION=tell_user
2022-05-26 15:24:34 : INFO  : zoom : NOTIFY=success
2022-05-26 15:24:34 : INFO  : zoom : LOGGING=DEBUG
2022-05-26 15:24:34 : INFO  : zoom : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2022-05-26 15:24:34 : INFO  : zoom : Label type: pkg
2022-05-26 15:24:34 : INFO  : zoom : archiveName: zoom.us.pkg
2022-05-26 15:24:34 : INFO  : zoom : no blocking processes defined, using zoom.us as default
2022-05-26 15:24:34 : DEBUG : zoom : Changing directory to /Users/dnikles/Documents/GitHub/Installomator/build
2022-05-26 15:24:34 : INFO  : zoom : App(s) found: /Applications/zoom.us.app
2022-05-26 15:24:34 : INFO  : zoom : found app at /Applications/zoom.us.app, version 5.10.6.7526, on versionKey CFBundleVersion
2022-05-26 15:24:34 : INFO  : zoom : appversion: 5.10.6.7526
2022-05-26 15:24:34 : INFO  : zoom : Latest version of zoom.us is 5.10.6.7526
2022-05-26 15:24:34 : WARN  : zoom : DEBUG mode 1 enabled, not exiting, but there is no new version of app.
2022-05-26 15:24:34 : REQ   : zoom : Downloading https://zoom.us/client/latest/ZoomInstallerIT.pkg to zoom.us.pkg
2022-05-26 15:24:36 : DEBUG : zoom : File list: -rw-r--r--  1 root  staff   112M May 26 15:24 zoom.us.pkg
2022-05-26 15:24:36 : DEBUG : zoom : File type: zoom.us.pkg: xar archive compressed TOC: 4814, SHA-1 checksum
2022-05-26 15:24:36 : DEBUG : zoom : curl output was:
*   Trying 170.114.10.71:443...
* Connected to zoom.us (170.114.10.71) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
} [312 bytes data]
* (304) (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3913 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Jose; O=Zoom Video Communications, Inc.; CN=*.zoom.us
*  start date: Apr 29 00:00:00 2022 GMT
*  expire date: May  2 23:59:59 2023 GMT
*  subjectAltName: host "zoom.us" matched cert's "zoom.us"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x13b811400)
> GET /client/latest/ZoomInstallerIT.pkg HTTP/2
> Host: zoom.us
> user-agent: curl/7.79.1
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 302 
< date: Thu, 26 May 2022 19:24:35 GMT
< content-length: 0
< location: https://cdn.zoom.us/prod/5.10.6.7526/ZoomInstallerIT.pkg
< x-zm-trackingid: v=2.0;clid=aw1;rid=WEB_08ff13e7765a8a247fba7c2e70228414
< x-content-type-options: nosniff
< content-security-policy: upgrade-insecure-requests; default-src https://*.zoom.us https://zoom.us blob: 'self'; img-src https: about: blob: data: 'self'; style-src https: safari-extension: chrome-extension: 'unsafe-inline' data: 'self'; font-src https: safari-extension: chrome-extension: blob: data: 'self'; connect-src * about: blob: data: 'self'; media-src * rtmp: blob: data: 'self'; frame-src https: ms-appx-web: zoommtg: zoomus: wvjbscheme: data: 'self'; object-src 'none'; base-uri 'none';
< x-frame-options: SAMEORIGIN
< set-cookie: zm_aid=""; Domain=.zoom.us; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly
< set-cookie: zm_haid=""; Domain=.zoom.us; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly
< set-cookie: zm_tmaid=""; Domain=.zoom.us; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly
< set-cookie: zm_htmaid=""; Domain=.zoom.us; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly
< p3p: CP="NOI ADM DEV PSAi COM NAV OUR OTR STP IND DEM"
< set-cookie: _zm_ssid=aw1_c_qu-wXzqHRHSAIBVz5WA7-w; Domain=.zoom.us; Path=/; Secure; HttpOnly
< set-cookie: cred=154AC5D777FC3071FB632C4E44811C74; Path=/; Secure; HttpOnly
< set-cookie: _zm_ctaid=eR84vuzVQ_eRg85bMPuUBg.1653593075446.b98a83d8aa9584456436d77f104b5cc5; Domain=.zoom.us; Expires=Thu, 26-May-2022 21:24:35 GMT; Path=/; Secure; HttpOnly
< set-cookie: _zm_chtaid=917; Domain=.zoom.us; Expires=Thu, 26-May-2022 21:24:35 GMT; Path=/; Secure; HttpOnly
< x-zm-zoneid: VA
< set-cookie: _zm_mtk_guid=c4e3c7c159a145f084a66d0740c7189c; Domain=.zoom.us; Expires=Sat, 25-May-2024 19:24:35 GMT; Path=/; Secure
< strict-transport-security: max-age=31536000; includeSubDomains
< x-xss-protection: 1; mode=block
< referrer-policy: strict-origin-when-cross-origin
< 
{ [0 bytes data]
* Connection #0 to host zoom.us left intact
* Issue another request to this URL: 'https://cdn.zoom.us/prod/5.10.6.7526/ZoomInstallerIT.pkg'
*   Trying 13.224.213.253:443...
* Connected to cdn.zoom.us (13.224.213.253) port 443 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
} [316 bytes data]
* (304) (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* (304) (IN), TLS handshake, Unknown (8):
{ [10 bytes data]
* (304) (IN), TLS handshake, Certificate (11):
{ [3920 bytes data]
* (304) (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* (304) (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* (304) (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / AEAD-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=San Jose; O=Zoom Video Communications, Inc.; CN=*.zoom.us
*  start date: Apr 29 00:00:00 2022 GMT
*  expire date: May  2 23:59:59 2023 GMT
*  subjectAltName: host "cdn.zoom.us" matched cert's "*.zoom.us"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
> GET /prod/5.10.6.7526/ZoomInstallerIT.pkg HTTP/1.1
> Host: cdn.zoom.us
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/vnd.apple.installer+xml
< Content-Length: 117388549
< Connection: keep-alive
< Date: Thu, 26 May 2022 05:46:41 GMT
< Last-Modified: Mon, 23 May 2022 14:31:42 GMT
< Etag: "6d27a490a1ffce97f45e3fa07a532743-14"
< X-Amz-Server-Side-Encryption: AES256
< Accept-Ranges: bytes
< Server: AmazonS3
< Via: 1.1 3a9f76e15ac64134cc339fc4f9fb6a4c.cloudfront.net (CloudFront)
< Age: 49075
< Cross-Origin-Resource-Policy: cross-origin
< X-Cache: Hit from cloudfront
< X-Amz-Cf-Pop: PHL50-C1
< X-Amz-Cf-Id: ToHNfqiW8z5pidaXMNX8DEPhrmuGzQD3bBDq7ykjRq8IDFMaidwz0g==
< 
{ [15805 bytes data]
* Connection #1 to host cdn.zoom.us left intact

2022-05-26 15:24:36 : DEBUG : zoom : DEBUG mode 1, not checking for blocking processes
2022-05-26 15:24:36 : REQ   : zoom : Installing zoom.us
2022-05-26 15:24:36 : INFO  : zoom : Verifying: zoom.us.pkg
2022-05-26 15:24:36 : DEBUG : zoom : File list: -rw-r--r--  1 root  staff   112M May 26 15:24 zoom.us.pkg
2022-05-26 15:24:37 : DEBUG : zoom : File type: zoom.us.pkg: xar archive compressed TOC: 4814, SHA-1 checksum
2022-05-26 15:24:37 : DEBUG : zoom : spctlOut is zoom.us.pkg: accepted
2022-05-26 15:24:37 : DEBUG : zoom : source=Notarized Developer ID
2022-05-26 15:24:37 : DEBUG : zoom : override=security disabled
2022-05-26 15:24:37 : DEBUG : zoom : origin=Developer ID Installer: Zoom Video Communications, Inc. (BJ4HAAB9B3)
2022-05-26 15:24:37 : INFO  : zoom : Team ID: BJ4HAAB9B3 (expected: BJ4HAAB9B3 )
2022-05-26 15:24:37 : DEBUG : zoom : DEBUG enabled, skipping installation
2022-05-26 15:24:37 : INFO  : zoom : Finishing...
2022-05-26 15:24:48 : INFO  : zoom : App(s) found: /Applications/zoom.us.app
2022-05-26 15:24:48 : INFO  : zoom : found app at /Applications/zoom.us.app, version 5.10.6.7526, on versionKey CFBundleVersion
2022-05-26 15:24:48 : REQ   : zoom : Installed zoom.us, version 5.10.6.7526
2022-05-26 15:24:48 : INFO  : zoom : notifying
2022-05-26 15:24:48 : INFO  : zoom : running jamf recon
Retrieving inventory preferences from https://JAMFURL:8443/...
Finding extension attributes...
Locating accounts...
Locating applications...
Locating hard drive information...
Searching path: /System/Applications
Locating package receipts...
Locating printers...
Searching path: /Applications
Locating hardware information (macOS 12.4.0)...
Submitting data to https://JAMFURL:8443/...
<computer_id>123456</computer_id>
2022-05-26 15:25:01 : DEBUG : zoom : DEBUG mode 1, not reopening anything
2022-05-26 15:25:01 : REQ   : zoom : All done!
2022-05-26 15:25:01 : REQ   : zoom : ################## End Installomator, exit code 0 
```

### CODE REVIEW

**Comment by acodega** [comment]
If running Installomator via a Jamf policy you can configure it to run inventory (recon) after running Installomator. I'm not sure the usefulness of having this happen within Installomator.

**Comment by scriptingosx** [comment]
This would run recon after _every_ update from Installomator, potentially creating many redundant recons. I agree this should not part of Installomator, but setup in the policy in Jamf.

**Comment by dnikles** [comment]
It would run after a successful update, which is not what running recon after running installomator in a jamf policy would do. How would a recon be redundant if it is running after software is successfully installed? The point of this is to avoid unnecessary recons.

**Comment by dnikles** [comment]
Sorted out a more efficient way of doing this in jamf thanks to @scriptingosx 

> If I have multiple update policies, I put them all on a custom trigger. Then I have one policy that runs that custom trigger once per day with update inventory enabled. Then you can disable the normal “update inventory once per day” policy. And you won't get more than one recon per day, no matter how many updates run (or don't)

**Pull request closed without merging**
