### PR TITLE
Create proofpointautoupdater.sh

### PR DESCRIPTION
**Pull request by wantedwriter**
2023-06-16 15:51:52 : REQ   : proofpointautoupdater : ################## Start Installomator v. 10.4, date 2023-06-04
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : ################## Version: 10.4
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : ################## Date: 2023-06-04
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : ################## proofpointautoupdater
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : DEBUG mode 1 enabled.
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : setting variable from argument debug=1
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : name=Proofpoint Auto Updater
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : appName=
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : type=pkgInZip
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : archiveName=
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : downloadURL=https://app.us-east-1-op1.op.analyze.proofpoint.com/downloads/default/mac/autoupdater/observeit-autoupdater-OSX-1.2.0.4.tar.gz
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : curlOptions=
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : appNewVersion=
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : appCustomVersion function: Not defined
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : versionKey=CFBundleShortVersionString
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : packageID=
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : pkgName=
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : choiceChangesXML=
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : expectedTeamID=DJR63QYCGL
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : blockingProcesses=
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : installerTool=
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : CLIInstaller=
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : CLIArguments=
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : updateTool=
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : updateToolArguments=
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : updateToolRunAsCurrentUser=
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : BLOCKING_PROCESS_ACTION=tell_user
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : NOTIFY=success
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : LOGGING=DEBUG
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : Label type: pkgInZip
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : archiveName: Proofpoint Auto Updater.zip
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : no blocking processes defined, using Proofpoint Auto Updater as default
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : Changing directory to /Users/wgad/Desktop
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : name: Proofpoint Auto Updater, appName: Proofpoint Auto Updater.app
2023-06-16 15:51:52 : WARN  : proofpointautoupdater : No previous app found
2023-06-16 15:51:52 : WARN  : proofpointautoupdater : could not find Proofpoint Auto Updater.app
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : appversion: 
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : Latest version not specified.
2023-06-16 15:51:52 : REQ   : proofpointautoupdater : Downloading https://app.us-east-1-op1.op.analyze.proofpoint.com/downloads/default/mac/autoupdater/observeit-autoupdater-OSX-1.2.0.4.tar.gz to Proofpoint Auto Updater.zip
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : No Dialog connection, just download
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : File list: -rw-r--r--@ 1 root  staff   1.3M Jun 16 15:51 Proofpoint Auto Updater.zip
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : File type: Proofpoint Auto Updater.zip: gzip compressed data, last modified: Mon Aug  8 08:40:40 2022, from Unix, original size modulo 2^32 1383936
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : curl output was:
*   Trying 18.172.134.34:443...
* Connected to app.us-east-1-op1.op.analyze.proofpoint.com (18.172.134.34) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
} [348 bytes data]
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* (304) (IN), TLS handshake, Unknown (8):
{ [19 bytes data]
* (304) (IN), TLS handshake, Certificate (11):
{ [5920 bytes data]
* (304) (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* (304) (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* (304) (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / AEAD-AES128-GCM-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.login.oitroot.us-east-1-op1.op.observeit.net
*  start date: Mar  1 00:00:00 2023 GMT
*  expire date: Dec  3 23:59:59 2023 GMT
*  subjectAltName: host "app.us-east-1-op1.op.analyze.proofpoint.com" matched cert's "app.us-east-1-op1.op.analyze.proofpoint.com"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M01
*  SSL certificate verify ok.
* using HTTP/2
* h2h3 [:method: GET]
* h2h3 [:path: /downloads/default/mac/autoupdater/observeit-autoupdater-OSX-1.2.0.4.tar.gz]
* h2h3 [:scheme: https]
* h2h3 [:authority: app.us-east-1-op1.op.analyze.proofpoint.com]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x147812400)
> GET /downloads/default/mac/autoupdater/observeit-autoupdater-OSX-1.2.0.4.tar.gz HTTP/2
> Host: app.us-east-1-op1.op.analyze.proofpoint.com
> user-agent: curl/7.88.1
> accept: */*
> 
< HTTP/2 200 
< content-type: application/gzip
< content-length: 1354294
< date: Fri, 16 Jun 2023 00:29:33 GMT
< last-modified: Mon, 15 Aug 2022 11:42:49 GMT
< etag: "851b20d77fa2ff68c36ae8d830eef938"
< accept-ranges: bytes
< server: AmazonS3
< x-cache: Hit from cloudfront
< via: 1.1 21baf3773089b90a16ce8df9145450bc.cloudfront.net (CloudFront)
< x-amz-cf-pop: ORD56-P7
< x-amz-cf-id: njttgdTZRy83tqo_DPm1NyPU73iouS6pyZEG_VS19rJVuhQRX4rq-g==
< age: 73339
< 
{ [16049 bytes data]
* Connection #0 to host app.us-east-1-op1.op.analyze.proofpoint.com left intact

2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : DEBUG mode 1, not checking for blocking processes
2023-06-16 15:51:52 : REQ   : proofpointautoupdater : Installing Proofpoint Auto Updater
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : Unzipping Proofpoint Auto Updater.zip
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : Found pkg(s):
/Users/wgad/Desktop/observeit-autoupdater-OSX-1.2.0.4.pkg
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : found pkg: /Users/wgad/Desktop/observeit-autoupdater-OSX-1.2.0.4.pkg
2023-06-16 15:51:52 : INFO  : proofpointautoupdater : Verifying: /Users/wgad/Desktop/observeit-autoupdater-OSX-1.2.0.4.pkg
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : File list: -rw-r--r--  1 502  staff   444K Aug  8  2022 /Users/wgad/Desktop/observeit-autoupdater-OSX-1.2.0.4.pkg
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : File type: /Users/wgad/Desktop/observeit-autoupdater-OSX-1.2.0.4.pkg: xar archive compressed TOC: 4258, SHA-1 checksum
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : spctlOut is /Users/wgad/Desktop/observeit-autoupdater-OSX-1.2.0.4.pkg: accepted
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : source=Notarized Developer ID
2023-06-16 15:51:52 : DEBUG : proofpointautoupdater : origin=Developer ID Installer: Proofpoint, Inc (DJR63QYCGL)
2023-06-16 15:51:53 : INFO  : proofpointautoupdater : Team ID: DJR63QYCGL (expected: DJR63QYCGL )
2023-06-16 15:51:53 : DEBUG : proofpointautoupdater : DEBUG enabled, skipping installation
2023-06-16 15:51:53 : INFO  : proofpointautoupdater : Finishing...
2023-06-16 15:51:56 : INFO  : proofpointautoupdater : name: Proofpoint Auto Updater, appName: Proofpoint Auto Updater.app
2023-06-16 15:51:56 : WARN  : proofpointautoupdater : No previous app found
2023-06-16 15:51:56 : WARN  : proofpointautoupdater : could not find Proofpoint Auto Updater.app
2023-06-16 15:51:56 : REQ   : proofpointautoupdater : Installed Proofpoint Auto Updater
2023-06-16 15:51:56 : INFO  : proofpointautoupdater : notifying
2023-06-16 15:51:56 : DEBUG : proofpointautoupdater : DEBUG mode 1, not reopening anything
2023-06-16 15:51:56 : REQ   : proofpointautoupdater : All done!
2023-06-16 15:51:56 : REQ   : proofpointautoupdater : ################## End Installomator, exit code 0

### CODE REVIEW

**Comment by scriptingosx** [comment]
getting a "team ID not matching" error

```
2023-08-23 13:11:55 : REQ   : proofpointautoupdater : ################## Start Installomator v. 10.4, date 2023-08-23
2023-08-23 13:11:55 : INFO  : proofpointautoupdater : ################## Version: 10.4
2023-08-23 13:11:55 : INFO  : proofpointautoupdater : ################## Date: 2023-08-23
2023-08-23 13:11:55 : INFO  : proofpointautoupdater : ################## proofpointautoupdater
2023-08-23 13:11:55 : DEBUG : proofpointautoupdater : DEBUG mode 1 enabled.
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : name=Proofpoint Auto Updater
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : appName=
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : type=pkgInZip
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : archiveName=
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : downloadURL=https://app.us-east-1-op1.op.analyze.proofpoint.com/downloads/default/mac/autoupdater/observeit-autoupdater-OSX-1.2.0.4.tar.gz
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : curlOptions=
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : appNewVersion=
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : appCustomVersion function: Not defined
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : versionKey=CFBundleShortVersionString
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : packageID=
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : pkgName=
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : choiceChangesXML=
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : expectedTeamID=DJR63QYCGL
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : blockingProcesses=
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : installerTool=
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : CLIInstaller=
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : CLIArguments=
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : updateTool=
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : updateToolArguments=
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : updateToolRunAsCurrentUser=
2023-08-23 13:11:56 : INFO  : proofpointautoupdater : BLOCKING_PROCESS_ACTION=tell_user
2023-08-23 13:11:56 : INFO  : proofpointautoupdater : NOTIFY=success
2023-08-23 13:11:56 : INFO  : proofpointautoupdater : LOGGING=DEBUG
2023-08-23 13:11:56 : INFO  : proofpointautoupdater : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2023-08-23 13:11:56 : INFO  : proofpointautoupdater : Label type: pkgInZip
2023-08-23 13:11:56 : INFO  : proofpointautoupdater : archiveName: Proofpoint Auto Updater.zip
2023-08-23 13:11:56 : INFO  : proofpointautoupdater : no blocking processes defined, using Proofpoint Auto Updater as default
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : Changing directory to /Users/armin/BTSync/Work/Projects/Installomator/build
2023-08-23 13:11:56 : INFO  : proofpointautoupdater : name: Proofpoint Auto Updater, appName: Proofpoint Auto Updater.app
2023-08-23 13:11:56.586 mdfind[26737:1306771] [UserQueryParser] Loading keywords and predicates for locale "en_US"
2023-08-23 13:11:56.586 mdfind[26737:1306771] [UserQueryParser] Loading keywords and predicates for locale "en"
2023-08-23 13:11:56.622 mdfind[26737:1306771] Couldn't determine the mapping between prefab keywords and predicates.
2023-08-23 13:11:56 : WARN  : proofpointautoupdater : No previous app found
2023-08-23 13:11:56 : WARN  : proofpointautoupdater : could not find Proofpoint Auto Updater.app
2023-08-23 13:11:56 : INFO  : proofpointautoupdater : appversion: 
2023-08-23 13:11:56 : INFO  : proofpointautoupdater : Latest version not specified.
2023-08-23 13:11:56 : REQ   : proofpointautoupdater : Downloading https://app.us-east-1-op1.op.analyze.proofpoint.com/downloads/default/mac/autoupdater/observeit-autoupdater-OSX-1.2.0.4.tar.gz to Proofpoint Auto Updater.zip
2023-08-23 13:11:56 : DEBUG : proofpointautoupdater : No Dialog connection, just download
2023-08-23 13:11:57 : DEBUG : proofpointautoupdater : File list: -rw-r--r--  1 armin  staff   1.3M Aug 23 13:11 Proofpoint Auto Updater.zip
2023-08-23 13:11:57 : DEBUG : proofpointautoupdater : File type: Proofpoint Auto Updater.zip: gzip compressed data, last modified: Mon Aug  8 08:40:40 2022, from Unix, original size modulo 2^32 1383936
2023-08-23 13:11:57 : DEBUG : proofpointautoupdater : curl output was:
*   Trying 13.32.27.85:443...
* Connected to app.us-east-1-op1.op.analyze.proofpoint.com (13.32.27.85) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
} [348 bytes data]
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* (304) (IN), TLS handshake, Unknown (8):
{ [19 bytes data]
* (304) (IN), TLS handshake, Certificate (11):
{ [5920 bytes data]
* (304) (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* (304) (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* (304) (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / AEAD-AES128-GCM-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.login.oitroot.us-east-1-op1.op.observeit.net
*  start date: Mar  1 00:00:00 2023 GMT
*  expire date: Dec  3 23:59:59 2023 GMT
*  subjectAltName: host "app.us-east-1-op1.op.analyze.proofpoint.com" matched cert's "app.us-east-1-op1.op.analyze.proofpoint.com"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M01
*  SSL certificate verify ok.
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: app.us-east-1-op1.op.analyze.proofpoint.com]
* h2 [:path: /downloads/default/mac/autoupdater/observeit-autoupdater-OSX-1.2.0.4.tar.gz]
* h2 [user-agent: curl/8.1.2]
* h2 [accept: */*]
* Using Stream ID: 1 (easy handle 0x11e010a00)
> GET /downloads/default/mac/autoupdater/observeit-autoupdater-OSX-1.2.0.4.tar.gz HTTP/2
> Host: app.us-east-1-op1.op.analyze.proofpoint.com
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/2 200 
< content-type: application/gzip
< content-length: 1354294
< date: Wed, 23 Aug 2023 11:11:58 GMT
< last-modified: Mon, 15 Aug 2022 11:42:49 GMT
< etag: "851b20d77fa2ff68c36ae8d830eef938"
< accept-ranges: bytes
< server: AmazonS3
< x-cache: Miss from cloudfront
< via: 1.1 a4af9b42c2ec29f616825af32712c204.cloudfront.net (CloudFront)
< x-amz-cf-pop: FRA56-C2
< x-amz-cf-id: 2v84cV-nKomVqLY34BbKjKnBrG5ornN4_u85DLzzR2OTb4-O93S5lg==
< 
{ [7714 bytes data]
* Connection #0 to host app.us-east-1-op1.op.analyze.proofpoint.com left intact

2023-08-23 13:11:58 : DEBUG : proofpointautoupdater : DEBUG mode 1, not checking for blocking processes
2023-08-23 13:11:58 : REQ   : proofpointautoupdater : Installing Proofpoint Auto Updater
2023-08-23 13:11:58 : INFO  : proofpointautoupdater : Unzipping Proofpoint Auto Updater.zip
2023-08-23 13:11:58 : DEBUG : proofpointautoupdater : Found pkg(s):
/Users/armin/BTSync/Work/Projects/Installomator/build/Box.pkg
2023-08-23 13:11:58 : DEBUG : proofpointautoupdater : /Users/armin/BTSync/Work/Projects/Installomator/build/Addigy MDM Watchdog.pkg
2023-08-23 13:11:58 : DEBUG : proofpointautoupdater : /Users/armin/BTSync/Work/Projects/Installomator/build/SURFdrive.pkg
2023-08-23 13:11:58 : DEBUG : proofpointautoupdater : /Users/armin/BTSync/Work/Projects/Installomator/build/python-3.11.4-macos11.pkg
2023-08-23 13:11:58 : DEBUG : proofpointautoupdater : /Users/armin/BTSync/Work/Projects/Installomator/build/observeit-autoupdater-OSX-1.2.0.4.pkg
2023-08-23 13:11:58 : DEBUG : proofpointautoupdater : /Users/armin/BTSync/Work/Projects/Installomator/build/Escrow.Buddy-[0-9.]*.pkg
2023-08-23 13:11:58 : INFO  : proofpointautoupdater : found pkg: /Users/armin/BTSync/Work/Projects/Installomator/build/Box.pkg
2023-08-23 13:11:58 : INFO  : proofpointautoupdater : Verifying: /Users/armin/BTSync/Work/Projects/Installomator/build/Box.pkg
2023-08-23 13:11:58 : DEBUG : proofpointautoupdater : File list: -rw-r--r--  1 armin  staff    66M Aug 22 19:32 /Users/armin/BTSync/Work/Projects/Installomator/build/Box.pkg
2023-08-23 13:11:58 : DEBUG : proofpointautoupdater : File type: /Users/armin/BTSync/Work/Projects/Installomator/build/Box.pkg: xar archive compressed TOC: 5649, SHA-1 checksum
2023-08-23 13:11:58 : DEBUG : proofpointautoupdater : spctlOut is /Users/armin/BTSync/Work/Projects/Installomator/build/Box.pkg: accepted
2023-08-23 13:11:58 : DEBUG : proofpointautoupdater : source=Notarized Developer ID
2023-08-23 13:11:58 : DEBUG : proofpointautoupdater : origin=Developer ID Installer: Box, Inc. (M683GB7CPW)
2023-08-23 13:11:58 : INFO  : proofpointautoupdater : Team ID: M683GB7CPW (expected: DJR63QYCGL )
2023-08-23 13:11:58 : DEBUG : proofpointautoupdater : DEBUG mode 1, not reopening anything
2023-08-23 13:11:58 : ERROR : proofpointautoupdater : ERROR: Team IDs do not match!
2023-08-23 13:11:58 : REQ   : proofpointautoupdater : ################## End Installomator, exit code 5 
```

**Comment by wantedwriter** [comment]
I'm confused about why the team id in your test is M683GB7CPW. That's not the one specified in the in the label.

**Comment by scriptingosx** [comment]
my error... I did not clean up the `build` folder before running this. All is good!

**Comment by scriptingosx** [comment]
thank you!

**Pull request merged**
