### PR TITLE
Update Camtasia 2021

### PR DESCRIPTION
**Pull request by marcelpogorzelski**
Fixed `name` and added `appNewVersion`

### CODE REVIEW

**Comment by scriptingosx** [comment]
I am not familiar with app. Is Camtasia 2020 still available for download? Is it being updated independently? Are there reasons (licensing) people might want to _keep_ the 2020 version and _not_ update? Or this merely decorative change of the name?

**Comment by marcelpogorzelski** [comment]
I am unfortunately not familiar myself. I just updated it to the newest version and fixed the appNewVersion. Quick check on their website shows that older version are available.

**Comment by marcelpogorzelski** [comment]
I checked. It should be possible to make one for each version.I don't know if it's really needed.

**Comment by marcelpogorzelski** [comment]
Sorry for the new line blunder. FIxed it now

**Pull request merged**
